#!/bin/sh
# $Revision$

#if [ -z ${1} ]
#then
#	TAGBASE="."
#	cd `dirname $0`
#else
#	TAGBASE=${1}
#	cd ${TAGBASE}   || exit 1
#fi

SVN_REPO_NAME="gemeinschaft"

TAGBASE="."
cd `dirname $0`

if [ -d .svn ]
then
	PARTS=`LANG=C svn info ${TAGBASE} 2>>/dev/null | grep ^URL | awk '{print $2;}' | sed -e "s:^.*/${SVN_REPO_NAME}/::" | sed -e 's:/: :g'`
	#echo "PARTS: ${PARTS}"
	PART1=`echo "${PARTS}" | awk '{print $1;}'`
	#echo "PART1: ${PART1}"
	
	REV=`LANG=C svnversion -c ${TAGBASE} 2>>/dev/null | cut -d: -f2 | grep -o -E '[0-9]+' \
		| sed -e 's:^[0-9]$:0\0:' \
		| sed -e 's:^[0-9][0-9]$:0\0:' \
		| sed -e 's:^[0-9][0-9][0-9]$:0\0:' \
		| sed -e 's:^[0-9][0-9][0-9][0-9]$:0\0:' \
		| sed -e 's:^[0-9][0-9][0-9][0-9][0-9]$:0\0:'`
	#echo "REV: ${REV}"
	
	if [ "${PART1}" = "trunk" ]
	then
		echo "trunk-r${REV}"
		exit 0
	fi
	
	IS_TAG=0
	IS_BRANCH=0
	IS_TEAM_BRANCH=0
	
	for PART in ${PARTS}
	do
		
		if [ ${IS_TAG} != 0 ]
		then
			RESULT="${PART}"
			break
		fi
		
		if [ ${IS_BRANCH} != 0 ]
		then
			if [ -z ${RESULT} ]
			then
				RESULT="${PART}"
			else
				RESULT="${RESULT}-${PART}"
			fi
			break
		fi
		
		if [ ${IS_TEAM_BRANCH} != 0 ]
		then
			if [ -z ${RESULT} ]
			then
				RESULT="${PART}"
			else
				RESULT="${RESULT}-${PART}"
			fi
			continue
		fi
		
		if [ "${PART}" = "branches" ]
		then
			IS_BRANCH=1
			RESULT="branch"
			continue
		fi
		
		if [ "${PART}" = "tags" ]
		then
			IS_TAG=1
			continue
		fi
		
		if [ "${PART}" = "team" ]
		then
			IS_TEAM_BRANCH=1
			continue
		fi
		
	done
	
	if [ ${IS_TAG} != 0 ]
	then
		echo "${RESULT}"
		exit 0
	else
		if [ "${RESULT}" = "" ]
		then
			# neither in "tags" nor in "branches" nor in "team"
			RESULT="other"
		fi
		if [ ${IS_TEAM_BRANCH} != 0 ]
		then
			echo "team-${RESULT}-r${REV}"
		else
			echo "${RESULT}-r${REV}"
		fi
		exit 0
	fi
fi

echo "unknown"
exit 1
