#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define( 'GS_VALID', true );  /// this is a parent file

require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'lib/getopt.php' );
include_once( GS_DIR .'inc/gs-lib.php' );
include_once( GS_DIR .'inc/mb_str_pad.php' );


/***********************************************************
*    the shell parameters
***********************************************************/
$usage = 'Usage: '. baseName(__FILE__) .' [--sort-by-host]';

$opts = @getOptsNoMultiples( '',
	array(
		'sort-by-host'
	),
	$usage
);
$sort_by_host = array_key_exists('sort-by-host', $opts);


/***********************************************************
*    get BOI admin permissions
***********************************************************/

# connect to db
#
$db = gs_db_master_connect();
if (! $db) {
	echo "Could not connect to database.\n";
	exit(1);
}

# get permissions
#
if ($sort_by_host) {
	$order_by = '`u`.`user`, `h`.`comment`, `h`.`host`';
} else {
	$order_by = '`h`.`comment`, `h`.`host`, `u`.`user`';
}
$rs = $db->execute(
	'SELECT `u`.`user`, `h`.`host`, `h`.`comment` `host_title`, `p`.`roles` '.
	'FROM '.
		'`boi_perms` `p` JOIN '.
		'`users` `u` ON (`u`.`id`=`p`.`user_id`) JOIN '.
		'`hosts` `h` ON (`h`.`id`=`p`.`host_id`) '.
	'ORDER BY `u`.`user`'
	);

$sep = str_repeat('-',78);
echo $sep,"\n";
if (! $sort_by_host) {
echo '| ',    str_pad('user'      , 20, ' ', STR_PAD_RIGHT) ,' ';
}
echo '| ', mb_str_pad('host title', 25, ' ', STR_PAD_RIGHT) ,' ';
echo '| ',    str_pad('host'      , 15, ' ', STR_PAD_RIGHT) ,' ';
if ($sort_by_host) {
echo '| ',    str_pad('user'      , 20, ' ', STR_PAD_RIGHT) ,' ';
}
echo '| ',    str_pad('roles'     ,  5, ' ', STR_PAD_RIGHT) ,' ';
echo '|';
echo "\n";
echo $sep,"\n";
while ($r = $rs->fetchRow()) {
	if (! $sort_by_host) {
	echo '| ',    str_pad($r['user'      ], 20, ' ', STR_PAD_RIGHT) ,' ';
	}
	echo '| ', mb_str_pad($r['host_title'], 25, ' ', STR_PAD_RIGHT) ,' ';
	echo '| ',    str_pad($r['host'      ], 15, ' ', STR_PAD_RIGHT) ,' ';
	if ($sort_by_host) {
	echo '| ',    str_pad($r['user'      ], 20, ' ', STR_PAD_RIGHT) ,' ';
	}
	echo '| ',    str_pad($r['roles'     ],  5, ' ', STR_PAD_RIGHT) ,' ';
	echo '|';
	echo "\n";
}
echo $sep,"\n";


?>