#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define( 'GS_VALID', true );  /// this is a parent file

require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'lib/getopt.php' );
include_once( GS_DIR .'inc/gs-lib.php' );
include_once( GS_DIR .'inc/gs-fns/gs_host_by_id_or_ip.php');


/***********************************************************
*    the shell parameters
***********************************************************/
$usage = 'Usage: '. baseName(__FILE__) .' --user=<user> --host=<ip|id>';

$opts = @getOptsNoMultiples( '',
	array(
		'user=',
		'host='
	),
	$usage
);
if (! isSet($opts['user'])
||  ! isSet($opts['host'])) {
	gs_script_invalid_usage( $usage );
}


/***********************************************************
*    set BOI admin permissions
***********************************************************/

if (! preg_match( '/^[a-z0-9\-_.]+$/', $opts['user'] )) {
	echo "User must be alphanumeric.\n";
	exit(1);
}

# connect to db
#
$db = gs_db_master_connect();
if (! $db) {
	echo "Could not connect to database.\n";
	exit(1);
}

# get user_id
#
$user_id = (int)$db->executeGetOne( 'SELECT `id` FROM `users` WHERE `user`=\''. $db->escape($opts['user']) .'\'' );
if (! $user_id) {
	echo "User not found.\n";
	exit(1);
}

# check if host id/ip is valid
#
$host = gs_host_by_id_or_ip( $opts['host'] );
if (isGsError( $host )) {
	echo $host->getMsg() ,"\n";
	exit(1);
}
if (! is_array( $host )) {
	echo "Host not found.\n";
	exit(1);
}

# set permissions
#
$ok = $db->execute( 'DELETE FROM `boi_perms` WHERE `user_id`='. $user_id .' AND `host_id`='. (int)$host['id'] );
if (! $ok) {
	echo "Failed to set permissions.\n";
	exit(1);
}

echo "Done.\n";

?>