#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* gs-diallog-purge (C) 2009 LocaNet oHG
* Daniel Scheller <scheller@loca.net>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define("GS_VALID", true);  /// this is a parent file

require_once(dirname(__FILE__) ."/../inc/conf.php");
include_once(GS_DIR ."inc/db_connect.php");

if(gs_get_conf("GS_BUTTONDAEMON_USE"))
{
	include_once(GS_DIR ."inc/gs-fns/gs_ami_events.php");
}

$db = gs_db_master_connect();

$max_diallog_age = gs_get_conf("GS_PROV_DIAL_LOG_LIFE");

$diallog_purge_sql = "DELETE FROM `dial_log` WHERE `timestamp` < (UNIX_TIMESTAMP() - ". $db->escape($max_diallog_age) .")";

$db->execute($diallog_purge_sql);

$db->execute("ANALYZE TABLE `dial_log`");
$db->execute("OPTIMIZE TABLE `dial_log`");

if(gs_get_conf("GS_BUTTONDAEMON_USE"))
{
	gs_diallog_purge_ui();
}

?>
