#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define( 'GS_VALID', true );  /// this is a parent file

require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'lib/getopt.php' );
include_once( GS_DIR .'inc/gs-lib.php' );
include_once( GS_DIR .'inc/group-fns.php' );

/***********************************************************
*    the shell parameters
***********************************************************/
$usage = 'Usage: '. baseName(__FILE__) .' --group=<group> --permission=<group> --type=<type>';

$opts = @getOptsNoMultiples( '',
	array(
		'group=',
		'permission=',
		'type='
	),
	$usage
);
if (! isSet($opts['group'])
 || ! isSet($opts['permission'])
 || ! isSet($opts['type'])
 ) {
	gs_script_invalid_usage( $usage );
}

/***********************************************************
*    call the function
***********************************************************/

$group_id = gs_group_id_get($opts['group']);
if (isGsError( $group_id )) gs_script_error( $group_id->getMsg() );
if (! $group_id)            gs_script_error();

$permission_id = gs_group_id_get($opts['permission']);
if (isGsError( $permission_id )) gs_script_error( $permission_id->getMsg() );
if (! $permission_id)            gs_script_error();

$ret = @ gs_group_permission_del($group_id, $permission_id, $opts['type']);

if (isGsError( $ret )) gs_script_error( $ret->getMsg() );
if (! $ret)            gs_script_error();

echo "Group permission deleted.\n";


?>