#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define( 'GS_VALID', true );  /// this is a parent file

require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'lib/getopt.php' );
include_once( GS_DIR .'inc/gs-lib.php' );
include_once( GS_DIR .'inc/gs-fns/gs_host_add.php' );

/***********************************************************
*    the shell parameters
***********************************************************/
$usage = 'Usage: '. baseName(__FILE__) .' --host=<ip> --comment=<comment> [--sip-proxy=<ip>] [--sip-sbc=<ip>]';

$opts = @getOptsNoMultiples( '',
	array(
		'host=',
		'comment=',
//		'foreign=',
		'sip-proxy=',
		'sip-sbc='
	),
	$usage
);
if (! isSet($opts['host'])
 || ! isSet($opts['comment'])
// || ! isSet($opts['foreign'])
 ) {
	gs_script_invalid_usage( $usage );
}

//$opts['foreign'] = ($opts['foreign'] == '1' || $opts['foreign'] != '0' || $opts['foreign'] != '');
$opts['foreign'  ] = false;
$opts['group-id' ] = null;
$opts['prefix'   ] = '';

if (! isSet($opts['sip-proxy']))
	$opts['sip-proxy'] = null;
if (! isSet($opts['sip-sbc'  ]))
	$opts['sip-sbc'  ] = null;


/***********************************************************
*    call the function
***********************************************************/

$ret = @ gs_host_add( $opts['host'], $opts['comment'], $opts['foreign'], $opts['group-id'], $opts['prefix'], $opts['sip-proxy'], $opts['sip-sbc'] );
if (isGsError( $ret )) gs_script_error( $ret->getMsg() );
if (! $ret)            gs_script_error();
echo "Host added.\n";

?>