#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define( 'GS_VALID', true );  /// this is a parent file

require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'lib/getopt.php' );
include_once( GS_DIR .'inc/gs-lib.php' );
include_once( GS_DIR .'inc/gs-fns/gs_prov_groups_get.php' );
include_once( GS_DIR .'inc/mb_str_pad.php' );


/***********************************************************
*    the shell parameters
***********************************************************/
$usage = 'Usage: '. baseName(__FILE__);

$opts = @getOptsNoMultiples( '',
	array(
	),
	$usage
);



/***********************************************************
*    call the function
***********************************************************/
$groups = @ gs_prov_groups_get();
if (isGsError( $groups )) gs_script_error( $groups->getMsg() );
if (! $groups)            gs_script_error();

$fields = array(
	//'__mptt_level'          => 0,
	'level'                 => 0,
	'id'                    => 1,
	'name'                  => 1,
	'title'                 => 1,
	'softkey_profile_id'    => 1,
	'prov_param_profile_id' => 1
);
$fieldsAbbr = array(
	//'__mptt_level'          => 'level',
	'level'                 => 'level',
	'id'                    => 'id',
	'name'                  => 'name',
	'title'                 => 'title',
	'softkey_profile_id'    => 'softkey_profile_id',
	'prov_param_profile_id' => 'prov_param_profile_id'
);


if (gs_stdout_is_console()) {
	
	$fieldsPad = array(
		//'__mptt_level'          => STR_PAD_RIGHT,
		'level'                 => STR_PAD_RIGHT,
		'id'                    => STR_PAD_LEFT,
		'name'                  => STR_PAD_RIGHT,
		'title'                 => STR_PAD_RIGHT,
		'softkey_profile_id'    => STR_PAD_RIGHT,
		'prov_param_profile_id' => STR_PAD_RIGHT,
	);
	
	foreach ($fields as $field => $length) {
		if (strLen($fieldsAbbr[$field]) > $length)
			$fields[$field] = strLen($fieldsAbbr[$field]);
	}
	foreach ($groups as $i => $group) {
		$groups[$i]['level'] = str_repeat('.', (int)$group['__mptt_level']);
	}
	foreach ($groups as $ignore => $group) {
		foreach ($fields as $field => $length) {
			//$user[$field] = str_replace( '"', '\\"', $user[$field] );
			if (mb_strLen($group[$field]) > $length)
				$fields[$field] = mb_strLen($group[$field]);
		}
	}
	
	$header = '| ';
	foreach ($fields as $field => $length) {
		$header.= str_pad( $fieldsAbbr[$field], $length, ' ' ) .' | ';
	}
	$sep = str_repeat( '-', strLen($header)-1 );
	
	echo $sep, "\n";
	echo $header, "\n";
	echo $sep, "\n";
	foreach ($groups as $ignore => $group) {
		if ($group['__mptt_level'] === 0) continue;  # skip root node
		echo '| ';
		foreach ($fields as $field => $length) {
			echo mb_str_pad( $group[$field], $length, ' ', $fieldsPad[$field] ), ' | ';
		}
		echo "\n";
	}
	echo $sep, "\n";

}
else {
	
	echo '# ';
	foreach ($fields as $field => $length) {
		echo gs_add_c_slashes( $fieldsAbbr[$field] ) ,"\t";
	}
	echo "\n";
	
	foreach ($groups as $ignore => $group) {
		if ($group['__mptt_level'] === 0) continue;  # skip root node
		unset($fields['level']);
		$fields = array_merge(array('__mptt_level'=>2), $fields);
		foreach ($fields as $field => $length) {
			echo gs_add_c_slashes( $group[$field] ) ,"\t";
		}
		echo "\n";
	}
	
}

?>
