#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define( 'GS_VALID', true );  /// this is a parent file

require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'lib/getopt.php' );
include_once( GS_DIR .'inc/gs-lib.php' );
include_once( GS_DIR .'inc/gs-fns/gs_prov_group_change.php' );


/***********************************************************
*    the shell parameters
***********************************************************/
$usage = 'Usage: '. baseName(__FILE__) .' [--parent=<name>] --name=<name> --title=<title> [--softkey-profile-id=<id>] [--prov-param-profile-id=<id>] [--show-ext-modules=<num>]';

$opts = @getOptsNoMultiples( '',
	array(
		'parent=',
		'name=',
		'title=',
		'softkey-profile-id=',
		'prov-param-profile-id=',
		'show-ext-modules='
	),
	$usage
);
if (! isSet($opts['name'])
 || ! isSet($opts['title'])
 ) {
	gs_script_invalid_usage( $usage );
}

if (! array_key_exists('show-ext-modules', $opts)) {
	$opts['show-ext-modules'] === null;
} else {
	$opts['show-ext-modules'] = (int)$opts['show-ext-modules'];
}

if (! array_key_exists('parent', $opts))
	$opts['parent'] === null;


/***********************************************************
*    call the function
***********************************************************/
$ret = @ gs_prov_group_add_by_name( $opts['parent'], $opts['name'], $opts['title'], $opts['softkey-profile-id'], $opts['prov-param-profile-id'], $opts['show-ext-modules'] );

if (isGsError( $ret )) gs_script_error( $ret->getMsg() );
if (! $ret)            gs_script_error();
echo "Group added.\n";


?>
