#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define( 'GS_VALID', true );  /// this is a parent file

require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'lib/getopt.php' );
include_once( GS_DIR .'inc/gs-lib.php' );
include_once( GS_DIR .'inc/gs-fns/gs_queue_callforward_activate.php' );


/***********************************************************
*    the shell parameters
***********************************************************/
$usage = 'Usage: '. baseName(__FILE__) .' --queue=<ext> --source=internal|external --case=always|full|timeout|empty --active=no|std|var|vml|trl';

$opts = @getOptsNoMultiples( '',
	array(
		'queue=',
		'source=',
		'case=',
		'active='
	),
	$usage
);
if (! isSet($opts['queue'])
 || ! isSet($opts['source'])
 || ! isSet($opts['case'])
 || ! isSet($opts['active'])
 ) {
	gs_script_invalid_usage( $usage );
}


/***********************************************************
*    call the function
***********************************************************/
$ret = @ gs_queue_callforward_activate( $opts['queue'], $opts['source'], $opts['case'], $opts['active'] );
if (isGsError( $ret )) gs_script_error( $ret->getMsg() );
if (! $ret)            gs_script_error();
echo "Call forward set.\n";

?>