#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define( 'GS_VALID', true );  /// this is a parent file

require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'lib/getopt.php' );
include_once( GS_DIR .'inc/gs-lib.php' );
include_once( GS_DIR .'inc/gs-fns/gs_ringtones_get.php' );


/***********************************************************
*    the shell parameters
***********************************************************/
$usage = 'Usage: '. baseName(__FILE__) .' --user=<user> [--regen]';

$opts = @getOptsNoMultiples( '',
	array(
		'user=',
		'regen'
	),
	$usage
);
if (! isSet($opts['user'])) {
	gs_script_invalid_usage( $usage );
}


/***********************************************************
*    call the function
***********************************************************/
$ringtones = @ gs_ringtones_get( $opts['user'] );
if (isGsError( $ringtones )) gs_script_error( $ringtones->getMsg() );
if (! is_array($ringtones))  gs_script_error();

$sources = array('internal', 'external');

if (array_key_exists('regen', $opts)) {
	include_once( GS_DIR .'inc/quote_shell_arg.php' );
	foreach ($sources as $source) {
		$bellcore = @$ringtones[$source]['bellcore'];
		echo './gs-ringtone-set --user=',qsa($opts['user']),' --source=',qsa($source),' --bellcore=',((int)$bellcore),'' ,"\n";
	}
	exit(0);
}


$sep = "---------------------------------------------------------\n";
echo $sep;
echo "| source    | bellcore | custom                         |\n";
echo $sep;
foreach ($sources as $source) {
	echo '| ', str_pad($source,9,' '), ' | ', str_pad( 'dr'. @$ringtones[$source]['bellcore'], 8, ' ' ), ' | ', str_pad( @$ringtones[$source]['file'], 30, ' ' ), " |\n";
}
echo $sep;

?>