#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define( 'GS_VALID', true );  /// this is a parent file

require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'lib/getopt.php' );
include_once( GS_DIR .'inc/gs-lib.php' );
include_once( GS_DIR .'inc/gs-fns/gs_user_change.php' );


/***********************************************************
*    the shell parameters
***********************************************************/
$usage = 'Usage: '. baseName(__FILE__) .' --user=<user> --pin=<123456> --firstname=<firstname> --language=<language> --lastname=<lastname> --email=<email> --host=<id>|<ip> [--hide-pb] [--drop-call] --[drop-target=<number>] [--force] [--no-reload]' ;

$opts = @getOptsNoMultiples( '',
	array(
		'user=',
		'pin=',
		'firstname=',
		'lastname=',
		'language=',
		'email=',
		'host=',
		'force',
		'no-reload',
		'hide-pb',
		'drop-call',
		'drop-target='
	),
	$usage
);
if (! isSet($opts['user'])
 || ! isSet($opts['pin'])
 || ! isSet($opts['firstname'])
 || ! isSet($opts['lastname'])
 || ! isSet($opts['language'])
 || ! isSet($opts['email'])
 || ! isSet($opts['host'])
 ) {
	gs_script_invalid_usage( $usage );
}
$opts['force'] = array_key_exists('force', $opts);

$reload = !(array_key_exists('no-reload', $opts));

$hide_pb = (array_key_exists('hide-pb', $opts));

$drop_call = (array_key_exists('drop-call', $opts));

if (  !(array_key_exists('drop-target', $opts)) ) {
	$drop_target = '';
}
else {
	$drop_target = $opts['drop-target'];
}

/***********************************************************
*    call the function
***********************************************************/
$ret = @ gs_user_change( $opts['user'], $opts['pin'], $opts['firstname'], $opts['lastname'], $opts['language'], $opts['host'], $opts['force'], $opts['email'], $reload, $hide_pb, $drop_call, $drop_target );
if (isGsError( $ret )) gs_script_error( $ret->getMsg() );
if (! $ret)            gs_script_error();
echo "User changed.\n";


?>
