#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define( 'GS_VALID', true );  /// this is a parent file

require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'lib/getopt.php' );
include_once( GS_DIR .'inc/gs-lib.php' );


/***********************************************************
*    the shell parameters
***********************************************************/
$usage = 'Usage: '. baseName(__FILE__) .' --host=<host_id|ip_addr>';

$opts = @getOptsNoMultiples( '',
	array(
		'host='
	),
	$usage
);
if (! array_key_exists('host', $opts)) {
	gs_script_invalid_usage( $usage );
}



$host = gs_host_by_id_or_ip( $opts['host'] );
if (isGsError($host))  gs_script_error( $host->getMsg() );
if (! is_array($host)) gs_script_error();

$db = gs_db_master_connect();
if (! $db) {
	gs_script_error( 'Could not connect to database.' );
}

$phones = $db->execute(
	'SELECT `p`.`mac_addr`, `u`.`current_ip` '.
	'FROM '.
		'`phones` `p` JOIN '.
		'`users` `u` ON (`u`.`id`=`p`.`user_id`) '.
	'WHERE `u`.`host_id` = '. $host['id'] .' '.
	'ORDER BY `p`.`mac_addr`'
	);

$fields = array(
	'mac_addr'   => 17,
	'current_ip' => 15
);
$fieldsAbbr = array(
	'mac_addr'   => 'mac_addr',
	'current_ip' => 'current_ip'
);

if (gs_stdout_is_console()) {
	
	$fieldsPad = array(
		'mac_addr'   => STR_PAD_RIGHT,
		'current_ip' => STR_PAD_RIGHT
	);
	
	$sep = str_repeat('-', 39);
	echo $sep ,"\n";
	foreach ($fields as $field => $length) {
		echo '| ', str_pad( $fieldsAbbr[$field], $length, ' ' ) ,' ';
	}
	echo '|',"\n";
	echo $sep ,"\n";
	
	while ($r = $phones->fetchRow()) {
		$r['mac_addr'] = preg_replace('/:$/', '', preg_replace('/(.{2})/', '$1:', $r['mac_addr']));
		foreach ($fields as $field => $length) {
			echo '| ', str_pad( $r[$field], $length, ' ', $fieldsPad[$field] ) ,' ';
		}
		echo '|',"\n";
	}
	echo $sep ,"\n";
	
} else {
	
	echo '# ';
	foreach ($fields as $field => $length) {
		echo gs_add_c_slashes( $fieldsAbbr[$field] ) ,"\t";
	}
	echo "\n";
	
	while ($r = $phones->fetchRow()) {
		foreach ($fields as $field => $length) {
			echo gs_add_c_slashes( $r[$field] ) ,"\t";
		}
		echo "\n";
	}
	
}

?>