#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define( 'GS_VALID', true );  /// this is a parent file

require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'lib/getopt.php' );
include_once( GS_DIR .'inc/gs-lib.php' );


/***********************************************************
*    the shell parameters
***********************************************************/
$usage = 'Usage: '. baseName(__FILE__) .' --host=<host_id|ip_addr>';

$opts = @getOptsNoMultiples( '',
	array(
		'host='
	),
	$usage
);
if (! array_key_exists('host', $opts)) {
	gs_script_invalid_usage( $usage );
}



$host = gs_host_by_id_or_ip( $opts['host'] );
if (isGsError($host))  gs_script_error( $host->getMsg() );
if (! is_array($host)) gs_script_error();

$db = gs_db_master_connect();
if (! $db) {
	gs_script_error( 'Could not connect to database.' );
}

$phones = $db->execute(
	'SELECT `p`.`mac_addr`, `u`.`current_ip` '.
	'FROM '.
		'`users` `u` JOIN '.
		'`phones` `p` ON (`p`.`user_id`=`u`.`id`) '.
	'WHERE `u`.`host_id` = '. $host['id']
	);

$sep = str_repeat('-', 39);
echo $sep ,"\n";

echo "| " . str_pad( "current_ip", 16, " ", STR_PAD_BOTH) , " | ";
echo str_pad( "mac_addr" ,16, " ", STR_PAD_BOTH) . " |\n";

echo $sep ,"\n";

while ($r = $phones->fetchRow()) {
	echo '| ', str_pad($r['current_ip'], 16, ' ', STR_PAD_BOTH) ,' ';
	echo '| ', str_pad($r['mac_addr'  ], 16, ' ', STR_PAD_BOTH) ,' ';
	echo '|',"\n";
}

echo $sep ,"\n";

?>