#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define( 'GS_VALID', true );  /// this is a parent file

require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'lib/getopt.php' );
include_once( GS_DIR .'inc/gs-lib.php' );


/***********************************************************
*    the shell parameters
***********************************************************/
$usage = 'Usage: '. baseName(__FILE__);

$opts = @getOptsNoMultiples( '',
	array(
	),
	$usage
);


/***********************************************************
*    call the function
***********************************************************/
$hosts = @ gs_hosts_get();
if (isGsError( $hosts )) gs_script_error( $hosts->getMsg() );
if (! $hosts)            gs_script_error();

$fields = array(
	'id'         => 1,
	'host'       => 15,
	'comment'    => 1
);
$fieldsAbbr = array(
	'id'         => 'id',
	'host'       => 'host',
	'comment'    => 'comment'
);

if (gs_stdout_is_console()) {
	
	$fieldsPad = array(
		'id'         => STR_PAD_LEFT,
		'host'       => STR_PAD_RIGHT,
		'comment'    => STR_PAD_RIGHT
	);
	
	foreach ($fields as $field => $length) {
		if (strLen($fieldsAbbr[$field]) > $length)
			$fields[$field] = strLen($fieldsAbbr[$field]);
	}
	foreach ($hosts as $ignore => $host) {
		foreach ($fields as $field => $length) {
			//$user[$field] = str_replace( '"', '\\"', $user[$field] );
			if (strLen($host[$field]) > $length)
				$fields[$field] = strLen($host[$field]);
		}
	}
	
	$header = '| ';
	foreach ($fields as $field => $length) {
		$header.= str_pad( $fieldsAbbr[$field], $length, ' ' ) .' | ';
	}
	$sep = str_repeat( '-', strLen($header)-1 );
	
	echo $sep, "\n";
	echo $header, "\n";
	echo $sep, "\n";
	foreach ($hosts as $ignore => $host) {
		echo '| ';
		foreach ($fields as $field => $length) {
			echo str_pad( $host[$field], $length, ' ', $fieldsPad[$field] ), ' | ';
		}
		echo "\n";
	}
	echo $sep, "\n";

}
else {
	
	echo '# ';
	foreach ($fields as $field => $length) {
		echo gs_add_c_slashes( $fieldsAbbr[$field] ) ,"\t";
	}
	echo "\n";
	
	foreach ($hosts as $ignore => $host) {
		foreach ($fields as $field => $length) {
			echo gs_add_c_slashes( $host[$field] ) ,"\t";
		}
		echo "\n";
	}
	
}


?>