#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define( 'GS_VALID', true );  /// this is a parent file

require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'lib/getopt.php' );
include_once( GS_DIR .'inc/gs-lib.php' );


/***********************************************************
*    the shell parameters
***********************************************************/
$usage = 'Usage: '. baseName(__FILE__) .' [--host=<hostid>]';

$opts = @getOptsNoMultiples( '',
	array(
		'host='
	),
	$usage
);

if(!array_key_exists('host', $opts)) {

echo $usage . "\n";
exit();
}


$db = gs_db_master_connect();
if (! $db)  {
  echo "Could not connect to database." ;
  exit();
}


$id = $db->executeGetOne( 'SELECT `id` FROM `hosts` WHERE `id`='. $opts['host'] );

if($id != $opts['host'] ) {
  echo $opts['host'] . " is not an valid Hostid\n";
  exit();
}


$user_ids = $db->execute('SELECT id,current_ip FROM users WHERE `host_id` = '. $id);

for($i = 0; $i<39; $i++)
  echo "-";

echo "\n";

echo "| " . str_pad( "current_ip", 16, " ", STR_PAD_BOTH) , " | ";
echo str_pad( "mac_addr" ,16, " ", STR_PAD_BOTH) . " |\n";

for($i = 0; $i<39; $i++)
  echo "-";

echo "\n";

while ($r = $user_ids->fetchRow()) {

if(!strlen($r['current_ip']))
  continue;

$mac = $db->executeGetOne( 'SELECT `mac_addr` FROM `phones` WHERE `user_id`='. $r['id']);

if(!strlen($mac))
  continue;

   echo "| ". str_pad($r['current_ip'], 16, " ", STR_PAD_BOTH) , " | ";
   echo str_pad($mac, 16, " ", STR_PAD_BOTH) . " |\n";


}

for($i = 0; $i<39; $i++)
  echo "-";

echo "\n";


?>
