#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define( 'GS_VALID', true );  /// this is a parent file

require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'inc/gs-lib.php' );
include_once( GS_DIR .'inc/gs-fns/gs_pickupgroups_show.php' );
include_once( GS_DIR .'inc/mb_str_pad.php' );


/***********************************************************
*    call the function
***********************************************************/
$ret = @ gs_pickupgroups_show();
if (isGsError( $ret )) gs_script_error( $ret->getMsg() );
if (! $ret)            gs_script_error();
if (! is_array($ret))  gs_script_error();



$sep = "--------------------------------------------------------------";

echo $sep, "\n";
echo "| id     | title                                             |\n";
echo $sep, "\n";

foreach ($ret as $entry) {
	echo "| ", str_pad($entry['id'],6,' '), ' | ', mb_str_pad($entry['title'],50,' '), "|\n";
}

echo $sep, "\n\n";

?>