#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define( 'GS_VALID', true );  /// this is a parent file

require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'lib/getopt.php' );
include_once( GS_DIR .'inc/gs-lib.php' );
include_once( GS_DIR .'inc/mb_str_pad.php' );


/***********************************************************
*    the shell parameters
***********************************************************/
$usage = 'Usage: '. baseName(__FILE__) .' --pgroup=<id>';

$opts = @getOptsNoMultiples( '',
	array(
		'pgroup='
	),
	$usage
);
if (! isSet($opts['pgroup'])
 ) {
	gs_script_invalid_usage( $usage );
}


/***********************************************************
*    call the function
***********************************************************/
$ret = @ gs_pickupgroup_show( $opts['pgroup'] );
if (isGsError( $ret )) gs_script_error( $ret->getMsg() );
if (! $ret)            gs_script_error();
if (! is_array($ret))  gs_script_error();



$sep = "-----------------------------------------------------------------------------------------";

echo $sep, "\n";
echo '| Title: ', mb_str_pad( $ret['title'], 79, ' ' ), '|', "\n";
echo $sep, "\n";
echo "| User            | Ext.     | First name           | Last name                 | Host# |\n";
echo $sep, "\n";
$host_confict = false;
$host_id = false;
foreach ($ret['users'] as $username => $user) {
	echo '| ', str_pad( $username, 15, ' '), ' | ', str_pad( $user['name'], 8, ' '), ' | ', mb_str_pad( $user['firstname'], 20, ' '), ' | ', mb_str_pad( $user['lastname'], 25, ' '), ' |', str_pad( $user['host_id'], 6, ' ', STR_PAD_LEFT ), " |\n";
	if ($host_id && $host_id != $user['host_id'])
		$host_confict = true;
	if (! $host_id) $host_id = $user['host_id'];
}
echo $sep, "\n";
if ($host_confict) {
	echo "CONFICT: ALL MEMBERS OF A GROUP MUST BE ON THE SAME HOST!\n";
}
echo "\n";

?>