#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define( 'GS_VALID', true );  /// this is a parent file

require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'lib/getopt.php' );
include_once( GS_DIR .'inc/gs-lib.php' );


/***********************************************************
*    the shell parameters
***********************************************************/
$usage = 'Usage: '. baseName(__FILE__) .' --job=<id>';

$opts = @getOptsNoMultiples( '',
	array(
		'job='
	),
	$usage
);
if (! isSet($opts['job'])
) {
	gs_script_invalid_usage( $usage );
}
$job_id = (int)$opts['job'];


/***********************************************************
*    delete provisioning job
***********************************************************/

# connect to db
#
$db = gs_db_master_connect();
if (! $db) {
	echo "Could not connect to database.\n";
	exit(1);
}

# get job info (for better error messages)
#
$rs = $db->execute( 'SELECT `running` FROM `prov_jobs` WHERE `id`='.$job_id );
if (!($job = $rs->fetchRow())) {
	echo "No such job.\n";
	exit(1);
}
if ($job['running']) {
	echo "Cannot delete running job.\n";
	exit(1);
}

$ok = $db->execute( 'DELETE FROM `prov_jobs` WHERE `id`='.$job_id.' AND `running`=0 LIMIT 1' );
if (! $ok) {
	echo "Failed to delete job.\n";
	exit(1);
}
@$db->execute( 'OPTIMIZE TABLE `prov_jobs`' );

echo "Job deleted.\n";


?>