#!/bin/sh

#####################################################################
#            Gemeinschaft - asterisk cluster gemeinschaft
# 
# $Revision$
# 
# Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
# http://www.amooma.de/
# Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
# Philipp Kempgen <philipp.kempgen@amooma.de>
# Peter Kozak <peter.kozak@amooma.de>
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.
#####################################################################

### BEGIN INIT INFO
# Provides:          gs-extstated
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Should-Start:      $time asterisk
# Should-Stop:       $time asterisk
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Gemeinschaft/Asterisk extension state daemon
# Description:       Gemeinschaft/Asterisk extension state daemon
#                    connects to one (or more) Asterisk Manager
#                    Interfaces (AMI), reads the extension states,
#                    listens to extension state changes and acts as
#                    a proxy for the states.
### END INIT INFO

DAEMON=/opt/gemeinschaft/sbin/ast_extstated/ast_extstated
EXECUTABLE=`basename 'ast_extstated'`
DESC="Gemeinschaft Extension State Daemon"
ARGS=

if ! [ -x $DAEMON ] ; then
	echo "ERROR: $DAEMON not found"
	exit 1
fi

case "$1" in
	start)
		echo "Starting $DESC ..."
		start-stop-daemon --start --oknodo --chdir `dirname "$DAEMON"` \
			--exec $DAEMON -- $ARGS
		;;
	stop)
		echo "Stopping $DESC ..."
		killall -INT $EXECUTABLE 1>>/dev/null 2>>/dev/null
		sleep 1
		killall -INT $EXECUTABLE 1>>/dev/null 2>>/dev/null
		;;
	reload)
		echo "Reloading $DESC ..."
		killall -HUP $EXECUTABLE 1>>/dev/null 2>>/dev/null
		;;
	restart|force-reload)
		$0 stop
		sleep 2
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload|force-reload}" >&2
		exit 1
		;;
esac

exit 0
