#!/bin/sh

#####################################################################
#           Silver-Bullet Start Script 
# 
# Copyright 2010, AMOOMA GmbH, Bachstr. 126, 56566 Neuwied, Germany,
# http://www.amooma.de/
# Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
# Philipp Kempgen <philipp.kempgen@amooma.de>
# Peter Kozak <peter.kozak@amooma.de>
# 
#####################################################################

DAEMON=/opt/silverbullet/silverbullet
EXECUTABLE=`basename 'silverbullet'`
DESC="Gemeinschaft Silver Bullet Daemon"
ARGS=

if ! [ -x $DAEMON ] ; then
	echo "ERROR: $DAEMON not found"
	exit 1
fi

case "$1" in
	start)
	        echo -n "Starting $DESC: "
	        start-stop-daemon --start --pidfile /var/run/$EXECUTABLE.pid \
            	--make-pidfile --background --startas $DAEMON
		echo "$EXECUTABLE."
		;;

	stop)
		echo -n "Stopping $DESC: "
		start-stop-daemon --stop --quiet --oknodo \
		--pidfile /var/run/$EXECUTABLE.pid
		rm -f /var/run/$NAME.pid
		echo "$EXECUTABLE."
												          ;;
	reload)
		echo "Reloading $DESC ..."
		killall -HUP $EXECUTABLE 1>>/dev/null 2>>/dev/null
		;;

	restart|force-reload)
		$0 stop
		sleep 2
		$0 start
		;;

	*)
		echo "Usage: $0 {start|stop|restart|reload|force-reload}" >&2
		exit 1
		;;
esac

exit 0
