#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
*
* $Revision$
*
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
*
* Language code helper functions to ease handling of INTL_LANG etc.
* Copyright 2010 Daniel Scheller <scheller@loca.net>
* LocaNet oHG, Lindemannstr. 81, 44137 Dortmund, Germany
* http://www.loca.net
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define("GS_VALID", true); // parent

ini_set("implicit_flush", 1);
ob_implicit_flush(1);

require_once(dirName(__FILE__) ."/../inc/conf.php");
include_once(GS_DIR ."inc/db_connect.php");
include_once(GS_DIR ."inc/gs-lib.php");
include_once(GS_DIR ."inc/agi-fns.php");
include_once(GS_DIR ."inc/langhelper.php");

///////////////////////////////////////////////////////////////////////////
// get vars from commandline

$userid = trim(@$argv[1]);
$langformat = trim(@$argv[2]);

// make sure userid is valid (numeric)
if(!$userid) die();
if(!preg_match('/^\d+$/', $userid)) die();

// convert cli arg to internal define, bail out if unknown format is requested
switch($langformat)
{
	case "ast":
		$langformat_real = GS_LANG_FORMAT_AST;
		$langopt_real = GS_LANG_OPT_AST;
		break;
	case "gs":
		$langformat_real = GS_LANG_FORMAT_GS;
		$langopt_real = GS_LANG_OPT_GS;
		break;
	default:
		die();
		break;
}

// do stuff
$db = gs_db_slave_connect();

$userlang = gs_get_lang_user($db, $userid, $langformat_real);
if(!$userlang)
{
	$userlang = str_replace("_", "-", gs_get_lang_global($langopt_real, $langformat_real));
}

gs_agi_set_variable("gs_userlang", $userlang);

?>
