#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision: 0 $
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/


# this script is not just for Snom phones but others like
# Siemens as well!


define( 'GS_VALID', true );  /// this is a parent file

ini_set('implicit_flush', 1);
ob_implicit_flush(1);


$uname = trim(@$argv[1]);

if (! $uname) {
	die();
}


require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'inc/gs-lib.php' );

/*include_once( GS_DIR .'inc/db_connect.php' );



$db = gs_db_master_connect();

$current_ip = $db->executeGetOne(
'SELECT `u`.`current_ip`
FROM
	`ast_sipfriends` `s` JOIN
	`users` `u` ON (`u`.`id`=`s`.`_user_id`)
WHERE `s`.`name`=\''. $db->escape($uname) .'\''
);
if ($current_ip) {
	@file_get_contents( 'http://'. $current_ip .'/confirm.htm?REBOOT=yes' );
}
*/


//@exec( 'asterisk -rx \'sip notify snom-reboot '. $uname .'\' >>/dev/null 2>&1' );
//@exec( 'asterisk -rx \'sip prune realtime '. $uname .'\' >>/dev/null 2>&1' );

@ gs_prov_phone_checkcfg_by_ext( $uname, true );


?>