#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

# this script is not just for Snom phones but others like
# Siemens as well!

define( 'GS_VALID', true );  /// this is a parent file
require_once( dirName(__FILE__) .'/../inc/conf.php' );
require_once( GS_DIR .'lib/getopt.php' );
include_once( GS_DIR .'inc/gs-lib.php' );

$opts = getOptsMultiples('',
	array(
		'ext=',
		'ip='
	),
	'Wrong usage!'
);

foreach ($opts as $opt) {
	$opt[1] = trim($opt[1]);
	if ($opt[1] == '') continue;
	switch ($opt[0]) {
		case 'ext':
			@gs_prov_phone_checkcfg_by_ext( $opt[1], false );
			break;
		case 'ip':
			@gs_prov_phone_checkcfg_by_ip( $opt[1], false );
			break;
	}
}




/*
include_once( GS_DIR .'inc/db_connect.php' );

$db = gs_db_master_connect();

$current_ip = $db->executeGetOne(
'SELECT `u`.`current_ip`
FROM
	`ast_sipfriends` `s` JOIN
	`users` `u` ON (`u`.`id`=`s`.`_user_id`)
WHERE `s`.`name`=\''. $db->escape($ext) .'\''
);
if ($current_ip) {
	@file_get_contents( 'http://'. $current_ip .'/confirm.htm?REBOOT=yes' );
}

@exec( 'asterisk -rx \'sip notify snom-reboot '. $ext .'\' >>/dev/null 2>&1' );
@exec( 'asterisk -rx \'sip prune realtime '. $ext .'\' >>/dev/null 2>&1' );
*/


?>