#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
*
* Author: Henning Holtschneider <henning@loca.net>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define( 'GS_VALID', true );  /// this is a parent file
require_once( dirName(__FILE__) .'/../inc/conf.php' );
require_once( GS_DIR .'inc/agi-fns.php' );
require_once( GS_DIR .'inc/gs-fns/gs_queue_get.php' );

ini_set('implicit_flush', 1);
ob_implicit_flush(1);

$queue_name = trim(@$argv[1]);
if (! preg_match('/^\d+$/', $queue_name))  // is not just digits
	die();

include_once( GS_DIR .'inc/db_connect.php' );

$db = gs_db_slave_connect();

$queue = gs_queue_get( $queue_name );

if ( $queue['sysrec_id'] > 0 ) {
	$filename = $db->executeGetOne( 'SELECT `md5hashname` FROM `systemrecordings` WHERE id =' . $queue['sysrec_id'] );
	
	if ( strlen($filename) > 0 )
		echo 'SET VARIABLE sysrec_filename '. gs_agi_str_esc($filename) . "\n";
	
}


?>