#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$  
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

#
# This script is in fact not being executed from the dialplan.
#

define( 'GS_VALID', true );  /// this is a parent file

require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'inc/db_connect.php' );
include_once( GS_DIR .'inc/log.php' );
include_once( GS_DIR .'inc/get-listen-to-ids.php' );

$context = preg_replace('/[^a-z0-9\-_]/i', '', @$argv[1]);
$mailbox = preg_replace('/[^0-9]/', '',        @$argv[2]);
$num_vms =                           (int)trim(@$argv[3]);
# only messages in INBOX are counted

if ($context === '') {
	gs_log(GS_LOG_WARNING, "Context arg missing.");
	echo "Context arg missing.\n";
	exit(1);
}
if ($mailbox === '') {
	gs_log(GS_LOG_WARNING, "Mailbox arg missing.");
	echo "Mailbox arg missing.\n";
	exit(1);
}

//gs_log(GS_LOG_DEBUG, "vm-postexec: context $context, mailbox $mailbox, num $num_vms");
gs_log(GS_LOG_DEBUG, "Mailbox $mailbox: processing ...");


$path = '/var/spool/asterisk/voicemail/'.$context.'/'.$mailbox.'/';
if (! @chDir( $path )) {
	gs_log(GS_LOG_WARNING, "Could not chdir to \"$path\".");
	echo "Could not chdir to \"$path\".\n";
	exit(1);
}

$db = gs_db_master_connect();
if (! $db) {
	gs_log(GS_LOG_WARNING, "Could not connect to database.");
	echo "Could not connect to database.\n";
	exit(1);
}


function _mbox_to_userid( $mailbox )
{
	global $db;
	$uid = (int)$db->executeGetOne( 'SELECT `_user_id` FROM `ast_sipfriends` WHERE `name`=\''. $db->escape($mailbox) .'\'' );
	return ($uid > 0) ? $uid : null;
}

/*
function _userid_to_hostid( $user_id )
{
	global $db;
	$hid = (int)$db->executeGetOne( 'SELECT `host_id` FROM `users` WHERE `id`='. (int)$user_id );
	return ($hid > 0) ? $hid : null;
}
*/

if (! function_exists('__')) {
function __($str)
{
	return $str;
}
}

function email_notify( $mailbox, $uid, $info, $about, $email )
{
	global $db;
	
	$rs = $db->execute( 'SELECT `firstname`, `lastname` FROM `users` WHERE `id`='. $uid );
	if (!($user = $rs->getRow())) return false;
	$new_msgs = (int)$db->executeGetOne( 'SELECT COUNT(*) FROM `vm_msgs` WHERE `mbox`=\''. $db->escape($mailbox) .'\' AND `folder`=\'INBOX\' AND `listened_to`=0' );
	
	$vm_dir = '/var/spool/asterisk/voicemail/';
	$origfile = $vm_dir .'default/'. $mailbox .'/'. $info['fld'] .'/'. $info['file'] .'.alaw';
	$tmpfile_base = '/tmp/gs-vm-'. preg_replace('/[^0-9]/', '', $mailbox) .'-'. $info['fld'] .'-'. $info['file'];
	
	if (! file_exists($origfile)) {
		gs_log( GS_LOG_WARNING, "Voicemail \"$origfile\" not found on this node" );
		return false;
	}
	
	# delete files like /tmp/gs-vm-* with mtime < time()-5 minutes
	#
	@exec( 'find \'/tmp/\' -maxdepth 1 -name \'gs-vm-*\' -type f -mmin +5 | xargs rm -f 1>>/dev/null 2>>/dev/null' );
	
	# convert file from original format (aLaw) to WAV (signed linear PCM,
	# 8000 Hz sampling rate, 16 bits/sample)
	#
	
	$err=0; $out=array();
	@exec( 'sudo chmod a+r '. qsa($origfile) .' 1>>/dev/null 2>>/dev/null', $out, $err );
	if ($err != 0) {
		gs_log( GS_LOG_WARNING, "Can't read origfile \"$origfile\"" );
		return false;
	}
	
	$outfile = $tmpfile_base.'.wav';
	$cmd = 'sox -q -t al '. qsa($origfile) .' -r 8000 -c 1 -s -2 -t wav '. qsa($outfile) .' 2>>/dev/null';
	$err=0; $out=array();
	@exec( $cmd, $out, $err );
	if ($err != 0) {
		gs_log( GS_LOG_WARNING, 'Failed to convert voicemail file' );
		return false;
	}
	if (! file_exists($outfile)) {
		gs_log( GS_LOG_WARNING, 'Failed to convert voicemail file' );
		return false;
	}
	
	@exec('hostname 2>>/dev/null', $out, $err);
	if ($err == 0) {
		$hostname = trim(implode(' ', $out));
		if (! $hostname) $hostname = 'localhost';
	} else {
		$hostname = 'localhost';
	}
	
	$subject = sPrintF(__('Neue Voicemail von %s'),
		($info['cidnum'] .($info['cidname'] != '' ? ' ('.$info['cidname'].')' : '')) );
	
	$body = sPrintF(__('Hallo %s!'), trim($user['firstname'] .' '. $user['lastname'])) ."\n\n";
	
	$body.= str_replace(array('\\\\n','\\n'), array("\n","\n"),
		sPrintF(__('Eine neue Voicemail von %s\\nist für Sie eingegangen.'),
		($info['cidnum'] .($info['cidname'] != '' ? ' ('.$info['cidname'].')' : '')) )) ."\n\n";
	
	$display_exten = (subStr(@$about['exten'],0,2)==='vm' ? subStr(@$about['exten'],2) : @$about['exten']);
	$body.= str_replace(array('\\\\n','\\n'), array("\n","\n"),
		sPrintF(__('Die Voicemail erreichte Sie auf Durchwahl %s.'), $display_exten)) ."\n";
	
	$origdate_time = @strToTime(@$about['origdate']);
	if ($origdate_time > 0) {
		$origdate_display = date(__('d.m.Y, H:i T'), $origdate_time);  //FIXME
	} else {
		$origdate_display = @$about['origdate'];
	}
	$body.= __('Datum') .':  '. $origdate_display ."\n";
	
	$dur_m = floor(@$about['duration'] / 60) % 60;
	$dur_s = floor(@$about['duration']     ) % 60;
	if     ($dur_m > 0) $dur_str = sPrintF(__('%d Min. %d Sek.'), $dur_m, $dur_s);
	else                $dur_str = sPrintF(__(        '%d Sek.'),         $dur_s);
	$body.= __('Dauer') .':  '. $dur_str ."\n";
	$body.= "\n";
	$body.= str_replace(array('\\\\n','\\n'), array("\n","\n"),
		__('Sie finden die Voicemail im Anhang dieser Email.')) ."\n\n";
	
	if ($new_msgs == 1) {
		$body.= str_replace(array('\\\\n','\\n'), array("\n","\n"),
			sPrintF(__('Es befindet sich jetzt %d neue Voicemail in Ihrer Mailbox.'), 1)) ."\n";
	} else {
		$body.= str_replace(array('\\\\n','\\n'), array("\n","\n"),
			sPrintF(__('Es befinden sich jetzt %d neue Voicemails in Ihrer Mailbox.'), $new_msgs)) ."\n";
	}
	
	$body.= "\n";
	$body.= '-- ' ."\n";
	$body.= str_replace(array('\\\\n','\\n'), array("\n","\n"),
		__('Dies ist eine automatisierte Nachricht. Bitte antworten Sie nicht.')) ."\n";
	$body.= sPrintF(__('%s auf "%s"'), 'Gemeinschaft', $hostname) ."\n";
	
	$file_name = baseName($outfile);
	$GS_EMAIL_DELIVERY = gs_get_conf('GS_EMAIL_DELIVERY');
	
	if (! file_exists($outfile) || ! is_readable($outfile)) {
		gs_log( GS_LOG_WARNING, "Can\'t read outfile \"$outfile\"" );
		return false;
	}
	$fh = @fOpen($outfile, 'rb');
	if (! $fh) {
		gs_log( GS_LOG_WARNING, "Can\'t read outfile \"$outfile\"" );
		return false;
	}
	
	if ($GS_EMAIL_DELIVERY === 'sendmail') {
		
		include_once( GS_DIR .'inc/email-functions.php' );
		
		$boundary = '=_'.strToUpper(md5(uniqid(time())));
		$mail_headers = array();
		$mail_headers[] = "From: \"Gemeinschaft\" <root>";
		$mail_headers[] = "Reply-To: \"". 'Nicht antworten' ."\" <noreply@noreply.local>";
		$mail_headers[] = "MIME-Version: 1.0";
		$mail_headers[] = "Content-Type: multipart/mixed; boundary=\"$boundary\"";
		
		$mime_body = array();
		$mime_body[] = 'This is a multi-part message in MIME format.';
		$mime_body[] = 'Dies ist eine mehrteilige Nachricht im MIME-Format.';
		$mime_body[] = '';
		$mime_body[] = '--'.$boundary;
		$mime_body[] = 'Content-Type: text/plain; charset="utf-8"';
		//$mime_body[] = 'Content-Transfer-Encoding: 8bit';
		$mime_body[] = 'Content-Transfer-Encoding: quoted-printable';
		$mime_body[] = '';
		$mime_body[] = quoted_printable_encode_text( $body, "\n" );
		unset($body);
		$mime_body[] = '--'.$boundary;
		$mime_body[] = 'Content-Type: audio/x-wav; name="'.$file_name.'"';
		$mime_body[] = 'Content-Transfer-Encoding: base64';
		$mime_body[] = 'Content-Disposition: attachment; filename="'.$file_name.'"';
		$mime_body[] = '';
		$mime_body[] = rTrim(@chunk_split(@base64_encode(@fRead($fh, @fileSize($outfile)))), "\r\n");
		# chunk_split() adds "\r\n" in some but not all versions of PHP
		@fClose($fh);
		$mime_body[] = '';
		$mime_body[] = '--'.$boundary.'--';
		$mime_body[] = '';
		
		# Do not use "\r\n" to separate headers. That's a bug in the
		# PHP documentation (see http://bugs.php.net/bug.php?id=15841).
		# On Unix/Linux PHP's mail() function does not speak SMTP
		# directly but talks to the sendmail command which needs
		# normal line endings ("\n") - unless you are using Postfix
		# which understands either format.
		$ok = mail(
			$email,
			$subject,
			implode("\n", $mime_body),
			implode("\n", $mail_headers)
			);
		unset($mime_body);
		return $ok;
		
	}
	elseif ($GS_EMAIL_DELIVERY === 'direct-smtp') {
		
		require_once( GS_DIR .'lib/phpmailer/class.phpmailer.php' );
		$mail = new PHPMailer();
		$mail->CharSet = 'utf-8';
		$mail->SetLanguage(
			strToLower(subStr( gs_get_conf('GS_INTL_LANG'),0,2)),
			GS_DIR .'lib/phpmailer/language/' );
		$mail->Hostname = $hostname;
		$mail->From = 'root@'.$hostname;
		$mail->FromName = 'Gemeinschaft';
		$mail->AddReplyTo( '', 'Nicht antworten' );
		$mail->AddAddress($email,'','');
		$mail->Subject = $subject;
		$mail->Body = $body;
		unset($body);
		$mail->AddStringAttachment( @fRead($fh, @fileSize($outfile)), $file_name, 'base64', 'audio/x-wav' );
		@fClose($fh);
		$mail->IsSMTP();
		//$mail->SMTPDebug = true;
		$mail->Timeout = 10;
		if (! preg_match('/@([^@]+)/', $email, $m)) {
			$ok = false;
		} else {
			$host = $m[1];
			$mx_hosts   = array();
			$mx_weights = array();
			getMXRR($host, $mx_hosts, $mx_weights);
			$mxs = array();
			if (@count($mx_hosts) > 0) {
				for($i=0; $i<count($mx_hosts); ++$i) {
					$mxs[$mx_hosts[$i]] = @$mx_weights[$i];
				}
				aSort($mxs, SORT_NUMERIC);
			} else {
				$mxs[$host] = 0;  # RFC 2821
			}
			while (list($mx_host, $mx_weight) = each($mxs)) {
				@set_time_limit(30);
				$mail->Host = $mx_host;
				$ok = @$mail->Send();
				if ($ok) break;
			}
		}
		unset($mail);
		return $ok;
		
	}
}


$our_host_id = (int)gs_get_listen_to_primary_id();
if (! $our_host_id) {
	gs_log(GS_LOG_WARNING, "Could not get our primary host ID!");
	echo "Could not get our primary host ID!\n";
	exit(1);
}

$uniqueids = array();

$files = glob( '*/msg*.txt' );
foreach ($files as $filename) {
	$info = array();
	
	$tmp = explode('/', $filename, 3);
	
	$info['fld' ] =          @$tmp[0];
	$info['file'] = baseName(@$tmp[1],'.txt');
	
	$tmp = @gs_file_get_contents( $filename );
	$about = array();
	preg_match_all('/^([a-z]+) *= *([^\n\r]*)/mS', $tmp, $m, PREG_SET_ORDER);
	foreach ($m as $arr) {
		$about[$arr[1]] = $arr[2];
	}
	/*
	array
	(
		[origmailbox] => 2001
		[context] => to-internal-users-self
		[macrocontext] => 
		[exten] => 2001
		[priority] => 286
		[callerchan] => SIP/555-0823e0f8
		[callerid] => "Hans Test" <555>
		[origdate] => Thu Aug 16 12:59:40 AM CEST 2007
		[origtime] => 1187218780
		[category] => 
		[duration] => 7
	)
	*/
	
	if (preg_match('/<([^>]+)/S', @$about['callerid'], $m))
		$info['cidnum' ] = $m[1];
	else
		$info['cidnum' ] = '';
	
	if (preg_match('/^([^<]*)/S', @$about['callerid'], $m))
		$info['cidname'] = trim($m[1], ' "');
	else
		$info['cidname'] = '';
	
	$uniqueid = array(
		'mailbox'    =>              $mailbox     ,
		'origtime'   => (int)@$about['origtime'  ],
		'callerchan' =>      @$about['callerchan']
	);
	$uniqueids[] = $uniqueid;
	
	$send_notification = false;
	
	# check if we already know this message by unique signature
	# (mbox, origtime, callerchan)
	#
	gs_db_start_trans($db);
	$rs = $db->execute(
'SELECT
	`id`, `folder`, `file`
FROM `vm_msgs`
WHERE
	`mbox`=\''      . $db->escape(        $mailbox     ) .'\' AND
	`orig_time`='   .        (int)@$about['origtime'  ]  .' AND
	`callerchan`=\''. $db->escape(@$about['callerchan']) .'\''
	);
	if ($r = $rs->fetchRow()) {
		# we already know the message.
		# check if any of the data has changed and update the database entry:
		
		$changed = false;
		//$uid_curr = (int)$r['user_id'];
		//$update_mbox = '';
		//$update_uid  = '';
		
		/*
		if ($r['mbox'  ] != $mailbox) {
			gs_log(GS_LOG_DEBUG, "Mailbox $mailbox:  New message ". $info['fld'].'/'.$info['file'] ." (was forwarded from ". $r['mbox'] .")");
			$changed = true;
			$update_mbox = '`mbox`=\''. $db->escape($mailbox) .'\',';
			$uid_curr = _mbox_to_userid( $mailbox );
			$update_uid  = '`user_id`='. ($uid_curr ? $uid_curr : 'NULL') .',';
		}
		*/
		if ($r['folder'] != $info['fld' ]) {
			if (! $changed) {
				# if the mailbox has changed a debug message about the changed
				# folder is pointless
				gs_log(GS_LOG_DEBUG, "Mailbox $mailbox: A message was moved from folder ". $r['folder'] ." to ". $info['fld'] );
				$changed = true;
			}
		}
		if ($r['file'] != $info['file']) {
			if (! $changed) {
				# if the mailbox or the folder has changed a debug message
				# about the changed filename is pointless
				# apart from that, this will probably only occur if a
				# message was deleted in the same folder
				$changed = true;
			}
		}
		/*
		if ($r['host_id'] != $our_host_id) {
			# this can only happen if we're on some kind of a distributed file
			# system or if someone scp'ied the files from one host to another
			gs_log(GS_LOG_DEBUG, "Assuming distributed file system");
			$changed = true;
		}
		*/
		
		if ($changed) {
			//gs_log(GS_LOG_DEBUG, "Mailbox $mailbox: Message ". $info['fld'].'/'.$info['file'] ." has changed" );
			
			$ok = $db->execute(
'UPDATE `vm_msgs` SET
	`folder`=\''   . $db->escape(  $info['fld'        ]) .'\',
	`file`=\''     . $db->escape(  $info['file'       ]) .'\'
WHERE `id`='. (int)$r['id']
			);
		}
		else {
			gs_log(GS_LOG_DEBUG, "Mailbox $mailbox: No changes for message ". $info['fld'].'/'.$info['file'] );
		}
	}
	else {
		# we do not know the message.
		# insert it into the database:
		
		gs_log(GS_LOG_DEBUG, "Mailbox $mailbox: New message ". $info['fld'].'/'.$info['file'] );
		
		$uid_curr = (int)_mbox_to_userid( $mailbox );
		/*
		$uid_orig = (@$about['origmailbox'] == $mailbox)
			? $uid_curr
			: _mbox_to_userid( @$about['origmailbox'] );
		*/
		
		$ok = $db->execute(
'INSERT INTO `vm_msgs` (
	`id`,
	`host_id`,
	`mbox`,
	`user_id`,
	`orig_mbox`,
	`folder`,
	`file`,
	`orig_time`,
	`dur`,
	`callerchan`,
	`cidnum`,
	`cidname`,
	`listened_to`
) VALUES (
	NULL,
	'  .                     $our_host_id    .',
	\''. $db->escape(        $mailbox      ) .'\',
	'  .        ($uid_curr ? $uid_curr : 'NULL').',
	\''. $db->escape(@$about['origmailbox']) .'\',
	\''. $db->escape(  $info['fld'        ]) .'\',
	\''. $db->escape(  $info['file'       ]) .'\',
	'  .        (int)@$about['origtime'   ]  .',
	'  .        (int)@$about['duration'   ]  .',
	\''. $db->escape(@$about['callerchan' ]) .'\',
	\''. $db->escape(  $info['cidnum'     ]) .'\',
	\''. $db->escape(  $info['cidname'    ]) .'\',
	0
)'
		);
		if (! $ok)
			gs_log(GS_LOG_WARNING, "Mailbox $mailbox: Could not insert new message");
		$send_notification = $ok;
	}
	
	if (! gs_db_commit_trans($db)) {
		gs_log(GS_LOG_WARNING, "Mailbox $mailbox: Could not commit voicemail info to database!");
	}
	
	if (@$send_notification) {
		if ($uid_curr > 0) {
			$email_notify = (int)$db->executeGetOne( 'SELECT `email_notify` FROM `vm` WHERE `user_id`='. $uid_curr  );
			if ($email_notify == 1) {
				$email = $db->executeGetOne( 'SELECT `email` FROM `users` WHERE `id`='. $uid_curr );
				if ($email != '') {
					gs_log(GS_LOG_DEBUG, "Notify user_id $uid_curr, email \"$email\"" );
					$ok = email_notify( $mailbox, $uid_curr, $info, $about, $email );
					if (! $ok)
						gs_log(GS_LOG_WARNING, "Failed to send notification to \"$email\"" );
				}
			}
		}
	}
}

# find messages in the database which are not available as files,
# meaning they have been deleted:
#
$rs = $db->execute(
'SELECT `id`, `orig_time`, `callerchan`
FROM `vm_msgs`
WHERE `mbox`=\''. $db->escape($mailbox) .'\''
);
while ($r = $rs->fetchRow()) {
	$file_exists = false;
	foreach ($uniqueids as $uniqueid) {
		if ($uniqueid['origtime'  ] == $r['orig_time' ]
		&&  $uniqueid['callerchan'] == $r['callerchan'])
		{
			# is available as file
			$file_exists = true;
			break;
		}
	}
	if (! $file_exists) {
		gs_log(GS_LOG_DEBUG, "Mailbox $mailbox: A message was deleted");
		$ok = $db->execute( 'DELETE FROM `vm_msgs` WHERE `id`='. (int)$r['id'] );
		if (! $ok)
			gs_log(GS_LOG_WARNING, "Mailbox $mailbox: Could not delete message");
	}
}


?>
