#!/bin/bash
# Gemeinschaft
# $Revision$
# Replacement for Asterisk's safe_asterisk script.
# Don't mess around. Just start Asterisk and exit.

CLIARGS="$*"                    # Grab any args passed to safe_asterisk
ASTERISK=/usr/sbin/asterisk

# Don't die if stdout/stderr can't be written to
trap '' PIPE

# Start Asterisk
cd /tmp
${ASTERISK} ${CLIARGS}
ret=$?
exit $ret
