#!/usr/bin/expect

#####################################################################
#            Gemeinschaft - asterisk cluster gemeinschaft
# 
# $Revision$
# 
# Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
# http://www.amooma.de/
# Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
# Philipp Kempgen <philipp.kempgen@amooma.de>
# Peter Kozak <peter.kozak@amooma.de>
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.
#####################################################################


if {[llength $argv] != 2} {
    send_user "Params: 'sip:exten@host' timeout\n"
    exit 1
}
set sipuri [lindex $argv 0]
set timeout [lindex $argv 1]


# find sipsak
if       {[file executable /usr/local/bin/sipsak  ]} {
	set sipsak             /usr/local/bin/sipsak   ;
} elseif {[file executable /usr/local/sbin/sipsak ]} {
	set sipsak             /usr/local/sbin/sipsak  ;
} elseif {[file executable /usr/sbin/sipsak       ]} {
	set sipsak             /usr/sbin/sipsak        ;
} elseif {[file executable /usr/bin/sipsak        ]} {
	set sipsak             /usr/bin/sipsak         ;
} else                                               {
	set sipsak             sipsak                  ;
}


log_user 0
set timeout $timeout
set match_max 4000
spawn $sipsak -s $sipuri --hostname localhost -v
expect {
	-re "200 \[Oo\]\[Kk\]"    {send_user "OK\n"  ; exit 0;}
	-re "\[Nn\]ot \[Ff\]ound" {send_user "OK\n"  ; exit 0;}
	"timeout"                 {send_user "FAIL\n"; exit 1;}
	timeout                   {send_user "FAIL\n"; exit 1;}
}
send_user "FAIL\n";
exit 1

