#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define( 'GS_VALID', true );  /// this is a parent file
require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'lib/getopt.php' );
//require_once( GS_DIR .'inc/remote-exec.php' );
require_once( GS_DIR .'inc/quote_shell_arg.php' );
require_once( GS_DIR .'inc/find_executable.php' );



$usage = 'Usage: '. baseName(__FILE__) .' [--generate]';

$opts = @getOptsNoMultiples( '',
	array(
		'generate'
	),
	$usage
);

$generate_dialplan = array_key_exists('generate', $opts);


if ($generate_dialplan) {
	$err=0;
	@passThru( '/opt/gemeinschaft/sbin/gs-ast-dialplan-gen', $err );
	if ($err !== 0)
		echo "Failed to generate dialplan.\n";
	else
		echo "Dialplan generated.\n";
}


$asterisk = find_executable('asterisk',
	array('/usr/sbin/', '/usr/bin/', '/usr/local/sbin/', '/usr/local/bin/'));
if (! $asterisk) {
	echo "asterisk not found.\n";
	exit(0);
	# do not consider that an error
}

echo "Reloading the dialplan ...\n";
$err=0; $out=array();
@exec( $asterisk .' -rx \'extensions reload\' 1>>/dev/null', $out, $err );
$err=0; $out=array();
@exec( $asterisk .' -rx \'ael reload\' 1>>/dev/null', $out, $err );

echo "Dialplan reloaded.\n"


?>