#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2009, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define( 'GS_VALID', true );  /// this is a parent file
require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'lib/getopt.php' );
include_once( GS_DIR .'inc/gs-lib.php' );

/***********************************************************
*    the shell parameters
***********************************************************/
$usage = 'Usage: '. baseName(__FILE__) .' --ip=<ip>';

$opts = @getOptsNoMultiples( '',
	array(
		'ip='
	),
	$usage
);
if (! array_key_exists('ip' , $opts)) {
	gs_script_invalid_usage( $usage );
}

$prov_host = gs_get_conf('GS_PROV_HOST');

$xmlpi = '<'.'?xml version="1.0" encoding="UTF-8"?'.'>'."\n";
$xml = '<AastraIPPhoneExecute>' ."\n";
$xml.= '	<ExecuteItem URI="Command: Reset" />' ."\n";
$xml.= '</AastraIPPhoneExecute>' ."\n";
$data = "POST / HTTP/1.1\r\n";
$data.= "Host: ".$opts['ip']."\r\n";	
$data.= "Referer: $prov_host\r\n";
$data.= "Connection: Close\r\n";
$data.= "Content-Type: text/xml; charset=utf-8\r\n";
$data.= "Content-Length: ". (strLen('xml=') + strLen($xmlpi) + strLen($xml)) ."\r\n";
$data.= "\r\n";
$data.= 'xml='. $xmlpi . $xml;

$socket = @fSockOpen($opts['ip'] , 80, $error_no, $error_str, 4 );
if (! $socket) {
	gs_script_error('Failed to contact Aastra phone :'.$opts['ip']);
}
stream_set_timeout($socket, 4);
$bytes_written = (int)@fWrite($socket, $data, strLen($data));
@fFlush($socket);
$response = @fGetS($socket);
@fClose($socket);
if (strPos($response, '200') === false) {
	gs_script_error('Failed to contact Aastra phone :'.$opts['ip']);
}

?>