#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define( 'GS_VALID', true );  /// this is a parent file

require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'lib/getopt.php' );
include_once( GS_DIR .'inc/gs-lib.php' );


/***********************************************************
*    the shell parameters
***********************************************************/
$usage = 'Usage: '. baseName(__FILE__);

$opts = getOptsNoMultiples( '',
	array(
	),
	$usage
);



$file = '/tmp/gs-hylafax-hosts.hfaxd';
$fh = @fOpen($file,'w');
if (!$fh) {
	echo "Cannot open $file for writing! Please check access permissions!\n";
	exit(1);
}


$hf_admin = gs_get_conf('GS_FAX_HYLAFAX_ADMIN');
$hf_pass  = gs_get_conf('GS_FAX_HYLAFAX_PASS' );

if ($hf_admin != '') {
	$crypted = crypt($hf_pass, 'pF');
	$tmp = $hf_admin.'@:'.'0'.':'.$crypted.':'.$crypted ."\n";
	fWrite($fh, $tmp, strLen($tmp));
}


$db = gs_db_master_connect();
if (! $db) {
	echo "Could not connect to database.\n";
	exit(1);
}
$rs = $db->execute(
'SELECT `id`, `user`, `pin`
FROM `users`
WHERE `nobody_index` IS NULL
ORDER BY `id`'
);
if (! $rs) {
	echo "Error.\n";
	exit(1);
}

while ($user = $rs->fetchRow()) {
	$crypted = crypt($user['pin'], 'ml');
	$tmp = $user['user'].'@:'.$user['id'].':'.$crypted ."\n";
	fWrite($fh, $tmp, strLen($tmp));
}
fClose($fh);
echo "Written to $file\n";



$hf_host = gs_get_conf('GS_FAX_HYLAFAX_HOST');
$hf_port = gs_get_conf('GS_FAX_HYLAFAX_PORT');

$conn_id = @ftp_connect($hf_host, $hf_port);
if (! $conn_id) {
	echo "Could not connect to HylaFax server at ", $hf_host ,':', $hf_port ,"\n";
	exit(1);
}

$login_result = @ftp_login($conn_id, $hf_admin, $hf_pass);
//FIXME - This is a bit stupid as it requires that the
//user already exists on the HylaFax server.
if (! $login_result) {
	echo "Could not login at HylaFax server at ", $hf_host ,':', $hf_port ,"\n";
	exit(1);
}
if (! @ftp_raw($conn_id, 'admin '.$hf_pass)) {
	echo "Could not login as admin at HylaFax server at ", $hf_host ,':', $hf_port ,"\n";
	exit(1);
}

$remote_file = '/etc/hosts.hfaxd';

if (! @ftp_put($conn_id, $remote_file, $file, FTP_BINARY)) {
	echo "Failed to copy to HylaFax server at ", $hf_host ,':', $hf_port ,"\n";
	exit(1);
}
echo "Copied to HylaFax server at ", $hf_host ,':', $hf_port ,"\n";
echo "(You will probably need to restart the HylaFax daemon.)\n";


?>