#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/


define( 'GS_VALID', true );  /// this is a parent file
require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'inc/util.php' );
include_once( GS_DIR .'inc/mb_str_pad.php' );
include_once( GS_DIR .'inc/log.php' );
include_once( GS_DIR .'inc/db_connect.php' );



if ($argc < 2) {
	echo
	"  \n",
	"  Aufruf:\n",
	"  ", baseName($argv[0]) ," Monat\n",
	"  oder\n",
	"  ", baseName($argv[0]) ," Monat mail\n",
	"  \n",
	"  Monat im Format JJJJ-MM, also z.B. 2007-09\n",
	"  \n",
	"  Mit dem Parameter \"mail\" wird den Benutzern die jeweilige Auflistung\n",
	"  per E-Mail zugesendet.\n",
	"  \n";
	exit(1);
}
if (! preg_match('/^([0-9]{4})-([0-9]{2})$/', @$argv[1], $m)) {
	echo "Monat nicht erkannt!\n";
	exit(1);
}
$yyyy = $m[1];
$mm   = $m[2];

$send_email = false;
if ($argc > 2) {
	if (@$argv[2]==='mail') {
		$send_email = true;
	} else {
		echo "Parameter nicht erkannt!\n";
		exit(1);
	}
}

$GS_EMAIL_DELIVERY = gs_get_conf('GS_EMAIL_DELIVERY');


if (! defined('E_STRICT')) define('E_STRICT', 2048);

function _err_handler( $type, $msg, $file, $line )
{
	switch ($type) {
		case E_NOTICE:
		case E_USER_NOTICE:
			if (error_reporting() != 0) {  # suppressed by @
				gs_log( GS_LOG_NOTICE, 'PHP: '. $msg .' in '. $file .' on line '. $line );
			}
			break;
		case E_STRICT:
			if (error_reporting() != 0) {
				gs_log( GS_LOG_DEBUG, 'PHP (Strict): '. $msg .' in '. $file .' on line '. $line );
			} else {  # suppressed by @
				gs_log( GS_LOG_DEBUG, 'PHP (strict): '. $msg .' in '. $file .' on line '. $line );
			}
			break;
		default:
			gs_log( GS_LOG_FATAL  , 'PHP: '. $msg .' in '. $file .' on line '. $line );
			exit(1);
	}
}

/*
	Parameter: Abkuerzung der Tarifzone der Telekom mit 4
	alphanumerischen Zeichen.
	Rueckgabe: Name der Tarifzone (Abkuerzung)
*/
function telekom_tarifzone_k_to_v( $k )
{
	$k = preg_replace('/[^A-Z0-9]/S', '', strToUpper($k));
	$k0 = subStr($k,0,1);
	$k1 = subStr($k,1,1);
	$k2 = subStr($k,2,1);
	$k3 = subStr($k,3,1);
		
	$ret = '?-'.$k;
	switch ($k0) {
		case 'W':                                     # W
			//$ret = 'Deu?';
			$ret = 'Dtl';
			switch (subStr($k,1,3)) {
				case '001':                           # W001
				case '002':                           # W002
				case '801':                           # W801
				case '998':                           # W998
				case '999':                           # W999
					//$ret = 'Deu';
					$ret = 'Dtl';
					break;
			}
			break;
		case 'R':                                     # R
			//$ret = 'Deu?';
			$ret = 'Reg?';
			switch (subStr($k,1,3)) {
				case '001':                           # R001
				case '801':                           # R801
					//$ret = 'Deu';
					//$ret = 'Reg';
					$ret = 'Reg1';
					break;
				case '002':                           # R002
					$ret = 'Reg2';
					break;
			}
			break;
		case 'N':                                     # N
			//$ret = 'City?';
			$ret = 'Nah?';
			switch (subStr($k,1,3)) {
				case '001':                           # N001
				case '801':                           # N801
					//$ret = 'City';
					$ret = 'Nah';
					break;
			}
			break;
		case 'O':                                     # O
			//$ret = 'City?';
			$ret = 'Ort?';
			switch (subStr($k,1,3)) {
				case '001':                           # O001
				case '801':                           # O801
					//$ret = 'City';
					$ret = 'Ort';
					break;
			}
			break;
		case 'D':                                     # D
			$ret = 'D-Netz';
			switch (subStr($k,1,3)) {
				case '010':                           # D010
				case '175':                           # D175
					//$ret = 'D1';
					$ret = 'D1-Netz';
					break;
				case '176':                           # D176
					//$ret = 'D1Ext';
					$ret = 'D1-Netz';
					break;
				case '020':                           # D020
					//$ret = 'D2';
					$ret = 'D2-Netz';
					break;
			}
			break;
		case 'E':                                     # E
			$ret = 'E-Netz';
			switch (subStr($k,1,3)) {
				case '010':                           # E010
					//$ret = 'E1';
					$ret = 'E1-Netz';
					break;
				case '020':                           # E020
					//$ret = 'E2';
					$ret = 'E2-Netz';
					break;
			}
			break;
		case 'B':                                     # B
			$ret = 'Ausl/AuslF';
			switch ($k1) {
				case '0':                             # B0
					switch (subStr($k,2,2)) {
						case '11':                    # B011
						case '15':                    # B015
						case '21':                    # B021
						case '22':                    # B022
						case '24':                    # B024
						case '31':                    # B031
						case '41':                    # B041
						case '51':                    # B051
							$ret = 'Ausl';
							break;
						case '12':                    # B012
						case '13':                    # B013
						case '14':                    # B014
						case '16':                    # B016
						case '23':                    # B023
						case '32':                    # B032
						case '33':                    # B033
						case '35':                    # B035
						case '42':                    # B042
						case '43':                    # B043
						case '45':                    # B045
							$ret = 'AuslF';
							break;
					}
					break;
				case '1':                             # B1
					if ($k2>='0' && $k2<='5') {       # B10-B15
						if ($k3=='0')                 # B100-B150
							$ret = 'Ausl';
						elseif ($k3=='5' && $k2=='5') # B155
							$ret = 'Ausl';
					}
					break;
				case '2':                             # B2
					$k23 = subStr($k,2,2);
					if ($k23>='08' && $k23<='20')     # B208-B220
						$ret = 'Ausl';
					elseif ($k23=='03')               # B203
						$ret = 'Ausl';
					elseif ($k23>='04' && $k23<='07')
						$ret = 'AuslF';
					break;
				case '3':                             # B3
					switch (subStr($k,2,2)) {
						case '310':                   # B310
						case '311':                   # B311
							$ret = 'Ausl';
							break;
					}
					break;
			}
			break;
		case 'S':                                     # S
			// Sat/Sonder/Spezial/Sonstiges/Shared?
			$ret = 'Sonst?';
			switch ($k1) {
				case '0':                             # S0
					switch (subStr($k,2,2)) {
						case '01':                    # S001
						case '02':                    # S002
						case '03':                    # S003
						case '04':                    # S004
						case '05':                    # S005
						case '06':                    # S006
						case '10':                    # S010
							$ret = 'Inmar';
							break;
						case '09':                    # S009
							$ret = 'Emsat';
							break;
					}
					break;
				case '8':                             # S8
					if ($k2=='0')                     # S80
						// Anrufe auf 0180..
						// (shared cost), z.B.
						// S801 fuer Anruf auf 01801..
						$ret = 'Shared';
						// wie heisst das bei der Telekom?
					elseif (subStr($k,2,2) == '91') { # S891
						// Internet-by-Call?
						$ret = 'Onl';
					}
					break;
				case '1':                             # S1
					if (subStr($k,2,2) == '91') {     # S191
						// Internet-by-Call auf
						// 019.. ?
						$ret = 'Onl';
					}
					break;
				case '7':                             # S7
					if ($k2=='0') {                   # S70
						// Anrufe auf 0700..
						// (persoenliche Vanity-Nummern)
						$ret = 'PersV';
						// wie heisst das bei der Telekom?
					}
					break;
				case '3':                             # S3
					if ($k2=='7') {                   # S37
						// Anrufe auf 0137
						// MABEZ ("Massenverkehr zu bestimmten Zielen"),
						// d.h. Televoting, Gewinnspiele
						// z.B. S379 bei Anrufen auf 01379..
						//$ret = 'TeleVote';
						$ret = 'MaBeZ';
						// wie heisst das bei der Telekom?
					}
					break;
			}
			break;
		case 'M':                                     # M
			// Ausland Mobilfunk?
			$ret = 'AuslM';
			break;
		case 'I':                                     # I
			// Informationsdienste / Auskunft
			$ret = 'Info?';  // wie heisst das bei der Telekom?
			switch (subStr($k,1,3)) {
				case '033':                           # I033
				case '034':                           # I034
					// Anrufe auf Auskunft 11833 / 11834
					$ret = 'Info';
					// wie heisst das bei der Telekom?
					break;
			}
			break;
		case 'X':                                     # X
			switch (subStr($k,1,3)) {
				case '011':                           # X011
					$ret = 'T-Box';
					break;
				case '666':                           # X666
					// steht in der Telekom-Liste, aber ohne Text
					break;
				case '900':                           # X900
					// "innovative Dienst" auf Vorwahl 012?
					$ret = 'InnovD';
					// wie heisst das bei der Telekom?
					break;
			}
			break;
		case 'V':                                     # V
			if ($k == 'V032') {                       # V032
				// nicht ortsgebundene Vorwahl 032
				$ret = 'Ortsunab';
				// wie heisst das bei der Telekom?
			}
			break;
		case 'K':                                     # K
			$ret = 'Konf?';
			switch (subStr($k,1,3)) {
				case '001':                           # K001
				case '801':                           # K801
					$ret = 'Konf';
					break;
			}
			break;
		case 'C':                                     # C
			$ret = 'C-Netz';
			if ($k == 'C002') $ret = 'C-Box';         # C002
			break;
		case 'F':                                     # F
			$ret = 'Scall?';
			switch (subStr($k,1,3)) {
				case '001':                           # F001
				case '002':                           # F002
				case '003':                           # F003
				case '004':                           # F004
					$ret = 'Scall';
					break;
			}
			break;
		case 'T':                                     # T
			if ($k == 'T016') $ret = 'VueDxl';        # T016 (VüDxl)
			break;
		case '1':                                     # 1
			if ($k == '10TD') $ret = 'Dx-P';          # 10TD
			break;
		case '2':                                     # 2
			if ($k == '20TD') $ret = 'ISDN';          # 20TD
			break;
		case '3':                                     # 3
			if ($k == '30TD') $ret = 'GX25';          # 30TD
			break;
		case '4':                                     # 4
			if ($k == '40TD') $ret = 'LtLD';          # 40TD
			break;
	}
	
	return $ret;
}

function _get_user_by_ext( $ext )
{
	global $DB;
	
	$rs = $DB->execute(
'SELECT
	`u`.`firstname` `fn`, `u`.`lastname` `ln`, `u`.`email`
FROM
	`ast_sipfriends` `s` JOIN
	`users` `u` ON (`u`.`id`=`s`.`_user_id`)
WHERE
	`s`.`name`=\''. $DB->escape($ext) .'\''
);
	if ($u = $rs->fetchRow()) {
		return $u;
	} else {
		return array('fn'=>'', 'ln'=>'', 'email'=>'');
	}
}

function _echo_sum( $sum_charge, $user )
{
	global $sep_tbl, $sep_sum, $euro_sign, $sum_charge_total, $send_email;
	
	$sum_charge_total += $sum_charge;
	
	echo $sep_tbl;
	echo '| ', str_pad('Summe:',61,' ',STR_PAD_LEFT) ,' |', str_pad(number_format($sum_charge, 2, ',', ''),6,' ',STR_PAD_LEFT) ,' ', $euro_sign ,' |' ,"\n";
	echo $sep_sum;
	
	$out = @ob_get_clean();
	echo "\n";
	//echo "OUT {\n";
	echo $out;
	//echo "}\n";
	
	if ($send_email) {
		_send_out_via_email( $user, $out );
	}
}

function _send_out_via_email( $user, $table )
{
	global $yyyy, $mm, $GS_EMAIL_DELIVERY;
	
	if (trim(@$user['email']) == '') return false;
	
	$err=0; $out=array();
	@exec('hostname 2>>/dev/null', $out, $err);
	if ($err === 0) {
		$hostname = trim(implode(' ', $out));
		if (! $hostname) $hostname = 'localhost';
	} else {
		$hostname = 'localhost';
	}
	
	$msg = sPrintF(
"Hallo %s

Auflistung Ihrer Privatgespr\xC3\xA4che im Monat %s:

%s

Viele Gr\xC3\xBC\xC3\x9Fe!
-- 
Dies ist eine automatisierte Nachricht. Bitte antworten Sie nicht.
Gemeinschaft auf \"%s\"
",
		@$user['fn'] .' '. @$user['ln'],
		$yyyy .'-'. $mm,
		$table,
		$hostname
	);
	echo "E-Mail an <", $user['email'] ,">\n";
	
	if ($GS_EMAIL_DELIVERY === 'sendmail') {
		
		$headers =
			'From: "Administrator" <root>' ."\r\n".
			'Reply-To: "'. 'Nicht antworten' .'" <noreply@noreply.local>' ."\r\n".
			'MIME-Version: 1.0' ."\r\n".
			'Content-Type: text/plain; charset=utf-8';
		
		$ok = @mail( $user['email'], "Privatgespraeche $yyyy-$mm", $msg, $headers );
		
	}
	elseif ($GS_EMAIL_DELIVERY === 'direct-smtp') {
		
		require_once( GS_DIR .'lib/phpmailer/class.phpmailer.php' );
		$mail = new PHPMailer();
		$mail->CharSet = 'utf-8';
		$mail->SetLanguage(
			strToLower(subStr( gs_get_conf('GS_INTL_LANG') ,0,2)),
			GS_DIR .'lib/phpmailer/language/' );
		$mail->Hostname = $hostname;
		$mail->From = 'root@'.$hostname;
		$mail->FromName = 'Gemeinschaft';
		$mail->AddReplyTo( '', 'Nicht antworten' );
		$mail->AddAddress(
			$u['email'],
			(@$u['firstname'] != '' ? $u['firstname'] : '') .
			(@$u['lastname'] != '' ? ' '.$u['lastname'] : '')
			);
		$mail->Subject = "Privatgespr\xC3\xA4che $yyyy-$mm";
		$mail->Body = $msg;
		$mail->IsSMTP();
		//$mail->SMTPDebug = true;
		$mail->Timeout = 10;
		if (! preg_match('/@([^@]+)/', $u['email'], $m)) {
			$ok = false;
			//$action_info = sPrintF(__('Fehler beim Senden an "%s"'), $u['email']) .' (no host)';
		} else {
			$host = $m[1];
			$mx_hosts   = array();
			$mx_weights = array();
			getMXRR($host, $mx_hosts, $mx_weights);
			$mxs = array();
			if (@count($mx_hosts) > 0) {
				for($i=0; $i<count($mx_hosts); ++$i) {
					$mxs[$mx_hosts[$i]] = @$mx_weights[$i];
				}
				aSort($mxs, SORT_NUMERIC);
			} else {
				$mxs[$host] = 0;  # RFC 2821
			}
			//print_r($mxs);
			
			while (list($mx_host, $mx_weight) = each($mxs)) {
				//echo $mx_host ,"\n";
				@set_time_limit(30);
				$mail->Host = $mx_host;
				//echo "\n";
				$ok = @$mail->Send();
				//echo "\n";
				if ($ok) break;
			}
			
			//$action_info = $ok
			//	? sPrintF(__('Pa&szlig;wort wurde an "%s" gesendet'), $u['email'])
			//	: sPrintF(__('Fehler beim Senden an "%s"'), $u['email']) .' ('. $mail->ErrorInfo .')';
			//// we should remove HTML entities from $mail->ErrorInfo
		}
		
	}
	
	return $ok;
}


set_error_handler('_err_handler');

$DB     = gs_db_master_connect();
$CDR_DB = gs_db_cdr_master_connect();
if (! $CDR_DB)
	exit(1);

$euro_sign = "\xE2\x82\xAC";
$sep     = '+'. str_repeat('-',73) .'+' ."\n";
$sep_tbl = '+---------------+-------------------+---------+---------+-------+---------+' ."\n";
$sep_sum = '+---------------------------------------------------------------+---------+' ."\n";
$head    = '| Beginn        | Rufnummer         | Tarifz. | Dauer   | Einh. | Kosten  |' ."\n";

# `cdr`.`accountcode` is "prv-XXX"
$rs = $CDR_DB->execute(
'SELECT
	SUBSTR(`cdr`.`accountcode`,5) `ext`, `evn`.`start`, `evn`.`remote`, `evn`.`tariff_zone`, `evn`.`dur`, `evn`.`units`, `evn`.`cur`,
	ROUND(`evn`.`charge`*(1+`evn`.`vat`/100)*100)/100 `charge_gross`
FROM
	`itemized_bill` `evn` JOIN
	`ast_cdr` `cdr` ON (`evn`.`cdr_id`=`cdr`.`_id`)
WHERE
	`evn`.`start`>=\''.$yyyy.'-'.$mm.'-01 00:00:00\' AND
	`evn`.`start`<=\''.$yyyy.'-'.$mm.'-31 23:59:59\'
ORDER BY `ext`, `evn`.`start`'
);
$ext = '';
$sum_charge = 0.0;
$sum_charge_total = 0.0;
while ($r = $rs->fetchRow()) {
	
	if ($r['ext'] !== $ext) {
		
		if ($ext !== '') {
			_echo_sum( $sum_charge, $u );
		}
		
		
		
		$ext = $r['ext'];
		
		echo "\n";
		@ob_start();
		echo $sep;
		$u = _get_user_by_ext( $ext );
		echo '| ', mb_str_pad( 'Teilnehmer:  '. $ext .'  ('. $u['fn'] .' '. $u['ln'] .')', 71, ' ', STR_PAD_RIGHT, 'UTF-8') ,' |' ,"\n";
		echo $sep_tbl;
		echo $head;
		echo $sep_tbl;
		
		$sum_charge = 0.0;
	}
	
	echo
		'| ',
		//str_pad($r['ext'],5,' ') ,' | ',
		subStr($r['start'],8,2) ,'.  ', subStr($r['start'],11) ,' | ',
		//str_pad($r['remote'],18,' ') ,'| ',
		str_pad(subStr($r['remote'],0,-2).'xx',18,' ') ,'| ',
		//str_pad($r['tariff_zone'],4,' ') ,' ',
		str_pad(telekom_tarifzone_k_to_v($r['tariff_zone']),8,' ') ,'|',
		str_pad(lTrim(lTrim(sec_to_hours($r['dur']),'0'),':'),8,' ',STR_PAD_LEFT) ,' |',
		str_pad($r['units'],6,' ',STR_PAD_LEFT) ,' |',
		str_pad(number_format($r['charge_gross'], 2, ',', ''),6,' ',STR_PAD_LEFT) ,' ', $euro_sign ,' | ',
		"\n";
	$sum_charge += $r['charge_gross'];
}
if ($ext !== '') {
	_echo_sum( $sum_charge, $u );
}

echo "\n\nGesamtkosten der Privatgespr\xC3\xA4che im Monat $yyyy-$mm:  ", number_format($sum_charge_total, 2, ',', '') ," $euro_sign (inkl. MwSt.)\n";


echo "\n";

?>