#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2009, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* 
* Sebastian Ertz
* Philipp Kempgen <philipp.kempgen@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define( 'GS_VALID', true );  /// this is a parent file
require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'lib/getopt.php' );
include_once( GS_DIR .'inc/gs-lib.php' );
include_once( GS_DIR .'inc/quote_shell_arg.php' );

/***********************************************************
*    the shell parameters
***********************************************************/
$usage = 'Usage: '. baseName(__FILE__) .' --ip=<ip>';

$opts = @getOptsNoMultiples( '',
	array(
		'ip='
	),
	$usage
);
if (! array_key_exists('ip' , $opts)) {
	gs_script_invalid_usage( $usage );
}
if (! preg_match('/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$/', $opts['ip'])) {
	echo "Invalid IP address.\n";
	exit(1);
}

//$prov_host = gs_get_conf('GS_PROV_HOST');

$cookiefile = '/tmp/gs-grandstream-cookie-'.time().'-'.rand(100000,999999);

# login
#
for ($i=0; $i<10; ++$i) {
	$err=0; $out=array();
	exec( 'wget -O /dev/null -o /dev/null --tries=1 --timeout=8 --retry-connrefused --save-cookies='. qsa($cookiefile) .' --keep-session-cookies --post-data='. qsa('P2='. rawUrlEncode(gs_get_conf('GS_GRANDSTREAM_PROV_HTTP_PASS')) .'&Login=Login&gnkey=0b82') .' -q '. qsa('http://'.$opts['ip'].'/dologin.htm') .' >>/dev/null 2>>/dev/null', $out, $err );
	if ($err == 0) break;
	sleep(1);
}

# reboot
#
$err=0; $out=array();
exec( 'wget -O /dev/null -o /dev/null --tries=3 --timeout=8 --retry-connrefused --load-cookies='. qsa($cookiefile) .' --keep-session-cookies -q '. qsa('http://'.$opts['ip'].'/rs.htm') .' >>/dev/null 2>>/dev/null &', $out, $err );

# delete cookiefile
#
if (file_exists($cookiefile))
	unlink($cookiefile);

?>