#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define( 'GS_VALID', true );  /// this is a parent file

require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'lib/getopt.php' );
include_once( GS_DIR .'inc/gs-lib.php' );
include_once( GS_DIR .'inc/gs-fns/gs_prov_phone_checkcfg.php' );
include_once( GS_DIR .'inc/gs-fns/gs_user_del.php' );

function _info( $message )
{
	global $silent;
	if (! $silent) echo $message,"\n";
}

function _have_prov_siemens()
{
	global $db;
	return (@$db->executeGetOne( 'SHOW TABLES LIKE \'prov_siemens\'' ) === 'prov_siemens');
}

/*
function _delete_nobody_user( $nobody_index )
{
	global $db;

	$user_id = (int)$db->executeGetOne( 'SELECT `id` FROM `users` WHERE `nobody_index`='. (int)$nobody_index );
	
	if (! $user_id) {
		_info( "Failed to find user for nobody user index $nobody_index." );
		return false;
	}
	
	//FIXME - see gs_user_del()
	// there's much more to delete
	
	//FIXME - call BOI API for foreign user
	_info( "FIXME - Not implemented." );
	return false;
	
	
	# delete sip peer
	#
	$db->execute( 'DELETE FROM `ast_sipfriends` WHERE `_user_id`='. $user_id );
	
	# delete dial log
	#
	$ok = $db->execute( 'DELETE FROM `dial_log` WHERE `user_id`='. $user_id );
	
	# delete user
	#
	$ok = $db->execute( 'DELETE FROM `users` WHERE `id`='. $user_id );
	if (! $ok) {
		_info( "Failed to delete user $user_id (nobody index $nobody_index)." );
		return false;
	}
	
	return true;
}
*/

function _delete_phone( $mac_addr )
{
	global $db;
		
	gs_db_start_trans($db);
	
	$phone_id = (int)$db->executeGetOne( 'SELECT `id` FROM `phones` WHERE `mac_addr`=\''. $db->escape($mac_addr) .'\'' );
	if ($phone_id < 1) {
		_info( "Phone $mac_addr not found." );
		if (! gs_db_rollback_trans($db))
			_info( "Failed to rollback transaction!" );
		return false;
	}
	//$nobody_index = (int)$db->executeGetOne( 'SELECT `nobody_index` FROM `phones` WHERE `mac_addr`=\''. $db->escape($mac_addr) .'\'' );
	$nobody_user = $db->executeGetOne( 'SELECT `user` FROM `users` JOIN `phones` ON (`phones`.`nobody_index` = `users`.`nobody_index`) WHERE `mac_addr`=\''. $db->escape($mac_addr) .'\'' );
	/*
	if ($nobody_index < 1) {
		//FIXME - why does this script only work if a _nobody_ user is logged
		// in at a phone?
		_info( "User at phone $mac_addr is not a nobody user." );
		if (! gs_db_rollback_trans($db))
			_info( "Failed to rollback transaction!" );
		return false;
	}
	*/
	
	if (_have_prov_siemens()) {
		$db->execute( 'DELETE FROM `prov_siemens` WHERE `mac_addr`=\''. $db->escape($mac_addr) .'\'' );
	}
	
	$ok = $db->execute( 'DELETE FROM `phones` WHERE `mac_addr`=\''. $db->escape($mac_addr) .'\'' );
	if (! $ok) {
		_info( "Failed to delete phone $mac_addr." );
		if (! gs_db_rollback_trans($db))
			_info( "Failed to rollback transaction!" );
		return false;
	}
	
	/*
	$ok = _delete_nobody_user( $nobody_index );
	if (! $ok) {
		_info( "Failed to delete nobody user index $nobody_index" );
		if (! gs_db_rollback_trans($db))
			_info( "Failed to rollback transaction!" );
		return false;
	}
	*/
	$ret = @ gs_user_del( $nobody_user );
	if (isGsError($ret) || ! $ret) {
		_info( $ret->getMsg() );
		//gs_db_rollback_trans($db);
		//return false;
	}
	
	if (! gs_db_commit_trans($db)) {
		_info( "Failed to delete phone $mac_addr." );
		return false;
	}
	return true;
}

function _trigger_phone_by_user_id( $user_id )
{
	global $db;
	
	$username = $db->executeGetOne( 'SELECT `name` FROM `ast_sipfriends` WHERE `_user_id`='. (int)$user_id );
	if (! $username) {
		_info( "Failed to get user ID $user_id" );
		return false;
	}
	$ok = @ gs_prov_phone_checkcfg_by_user( $username, true );
	if (! $ok) {
		_info( "Failed to sync phone of user $username" );
		return false;
	}
	
	return true;
}


/***********************************************************
*    the shell parameters
***********************************************************/
$usage = 'Usage: '. baseName(__FILE__) .' (--mac=<mac-addr> | --days=<days-since-last-contact>) (--show|--trigger|--delete) [--silent]';

$opts = @getOptsNoMultiples( '',
	array(
		'mac=',
		'days=',
		'show',
		'trigger',
		'delete',
		'silent'
	),
	$usage
);
if (! array_key_exists('mac' , $opts)
&&  ! array_key_exists('days', $opts)
) {
	gs_script_invalid_usage( $usage );
}
$mac     = preg_replace('/[^0-9A-Z]/', '', strToUpper(@$opts['mac']));
$days    = (int)@$opts['days'];
$silent  = array_key_exists('silent', $opts);

if     (array_key_exists('show'   , $opts)) $action = 'show';
elseif (array_key_exists('trigger', $opts)) $action = 'trigger';
elseif (array_key_exists('delete' , $opts)) $action = 'delete';
else gs_script_invalid_usage( $usage );


/***********************************************************
*    get the phone IDs
***********************************************************/

# connect to db
#
$db = gs_db_master_connect();
if (! $db) {
	echo "Could not connect to database.\n";
	exit(1);
}

if (! _have_prov_siemens()) {
	echo "Implemented for Siemens phones only.\n";
	exit(1);
}

if ($days > 0) {
	
	$now = time();
	$timestamp = $now - (86400 * $days);
	
	$rs = @$db->execute(
		'SELECT '.
			'`p`.`id` `phone_id`, `p`.`mac_addr` `mac_addr`, `p`.`user_id` `user_id`, `p`.`nobody_index` `nobody_index`, `p`.`type` `type`, '.
			'`s`.`t_last_contact` `t_last_contact` '.
		'FROM '.
			'`phones` `p` JOIN '.
			'`prov_siemens` `s` ON (`s`.`mac_addr`=`p`.`mac_addr`) '.
		'WHERE '.
			'`p`.`type` LIKE \'siemens-os%\' AND '.
			'`s`.`t_last_contact` < '. $timestamp .' '.
		'ORDER BY `s`.`t_last_contact` DESC'
		);
	if (! $rs) {
		echo "DB error.\n";
		exit(1);
	}
	
	if ($action === 'show') {
		$sep = '+--------------------+----------------------+---------------------+------+';
		echo $sep,"\n";
		echo '| ', str_pad('Phone (MAC addr.)', 18,' ') ,' ';
		echo '| ', str_pad('Phone Type', 20,' ') ,' ';
		echo '| ', str_pad('Last Contact', 19,' ') ,' ';
		echo '| ', str_pad('Days', 4,' ') ,' ';
		echo '|',"\n";
		echo $sep,"\n";
	}
	while ($r = $rs->fetchRow()) {
		switch ($action) {
			
			case 'show':
				//_info( 'Found '.$r['type'].' phone '.$r['mac_addr'].', last contact '. date('Y-m-d H:i:s', $r['t_last_contact']) );
				echo '| ', str_pad($r['mac_addr'], 18,' ') ,' ';
				echo '| ', str_pad($r['type'], 20,' ') ,' ';
				echo '| ', date('Y-m-d H:i:s', $r['t_last_contact']) ,' ';
				echo '| ', str_pad(floor(($now - $r['t_last_contact'])/86400) ,4,' ',STR_PAD_LEFT) ,' ';
				echo '|',"\n";
				break;
			
			case 'trigger':
				_info( 'Triggering phone '.$r['mac_addr'].' (ID: '.$r['phone_id'].') ...' );
				_trigger_phone_by_user_id( $r['user_id'] );
				break;
			
			case 'delete':
				_info( 'Deleting phone '.$r['mac_addr'].' (ID: '.$r['phone_id'].') ...' );
				$ok = _delete_phone( $r['mac_addr'] );
				break;
		}
	}
	if ($action === 'show') {
		echo $sep,"\n";
	}
	
}
elseif ($mac) {
	
	switch ($action) {
		
		case 'show':
			echo "Show by MAC addr. not implemented.\n";
			exit(1);
			break;
		
		case 'trigger':
			echo "Trigger by MAC addr. not implemented.\n";
			exit(1);
			break;
		
		case 'delete':
			_info( "Deleting phone $mac ..." );
			$ok = _delete_phone( $mac );
			if (! $ok) {
				exit(1);
			}
			exit(0);
			break;
	}
}


?>