#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* Soeren Sprenger <soeren.sprenger@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define( 'GS_VALID', true );  /// this is a parent file

require_once( dirName(__FILE__) .'/../inc/conf.php' );
require_once( GS_DIR .'inc/log.php' );
require_once( GS_DIR .'inc/db_connect.php' );
require_once( GS_DIR .'inc/gs-lib.php' );
include_once( GS_DIR .'inc/gs-fns/gs_prov_phone_checkcfg.php' );

$DB = gs_db_master_connect();

foreach (array(1,0) as $immediate) {
	$rs = @$DB->execute(
		'SELECT `id`, `phone_id`, `type`, `minute`, `hour`, `day`, `month`, `dow` '.
		'FROM `prov_jobs` '.
		'WHERE '.
			'`trigger`=\'server\' AND '.
			'`immediate`='. ((int)$immediate) .' AND '.
			'`running`=0'
		);
	if (! $rs) {
		gs_log(GS_LOG_FATAL, 'Could not get prov_jobs!');
		exit(1);
	}
	
	while ($r = $rs->fetchRow()) {
		if ($immediate) {
			$rule_matches = true;
		} else {
			//FIXME - check if the cron rule matches
			gs_log(GS_LOG_DEBUG, 'Non-immediate prov jobs not implemented here yet');
			$rule_matches = false;
		}
		if ($rule_matches) {
			if ($r['type'] === 'settings') {
				gs_log(GS_LOG_DEBUG, 'Triggering phone ID '.$r['phone_id']);
				$ip = $DB->executeGetOne(
					'SELECT `u`.`current_ip` '.
					'FROM '.
						'`phones` `p` LEFT JOIN '.
						'`users` `u` ON (`u`.`id`=`p`.`user_id`) '.
					'WHERE `p`.`id`='. $r['phone_id']
					);
				if (! $ip) {
					gs_log(GS_LOG_NOTICE, 'Need to trigger phone '.$r['phone_id'].' but can\'t get the IP address');
					continue;
				}
				gs_prov_phone_checkcfg_by_ip($ip);
				# delete job from DB
				$ok = $DB->execute( 'DELETE FROM `prov_jobs` WHERE `id`='.$r['id'] );
				if (! $ok)
					gs_log(GS_LOG_WARNING, 'Failed to delete prov-job ID '.$r['id'] );
			}
			/*
			elseif ($r['type'] === 'firmware') {
				//TODO: add here a check for firmware jobs
			}
			*/
		}
	}
}

exit(0);

?>