#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define( 'GS_VALID', true );  /// this is a parent file
require_once( dirName(__FILE__) .'/../inc/conf.php' );
include_once( GS_DIR .'lib/getopt.php' );
require_once( GS_DIR .'inc/remote-exec.php' );
require_once( GS_DIR .'inc/quote_shell_arg.php' );
require_once( GS_DIR .'inc/find_executable.php' );



$usage = 'Usage: '. baseName(__FILE__) .' [--dialplan]';

$opts = @getOptsNoMultiples( '',
	array(
		'dialplan'
	),
	$usage
);

$only_dialplan = array_key_exists('dialplan', $opts);


$err=0;
@passThru( '/opt/gemeinschaft/sbin/gs-ast-dialplan-gen', $err );
if ($err !== 0)
	echo "Failed to generate dialplan.\n";
else
	echo "Dialplan generated.\n";


$asterisk = find_executable('asterisk',
	array('/usr/sbin/', '/usr/bin/', '/usr/local/sbin/', '/usr/local/bin/'));
if (! $asterisk) {
	echo "asterisk not found!\n";
	exit(1);
}

if ($only_dialplan) {
	echo "Reloading only the Dialplan ...\n";
	$start_ast = false;
	$err=0; $out=array();
	@exec( $asterisk .' -rx \'extensions reload\' 1>>/dev/null', $out, $err );
	$start_ast = $start_ast || ($err != 0);
	$err=0; $out=array();
	@exec( $asterisk .' -rx \'ael reload\' 1>>/dev/null', $out, $err );
	$start_ast = $start_ast || ($err != 0);
} else {
	echo "Reloading Asterisk ...\n";
	$err=0; $out=array();
	@exec( $asterisk .' -rx \'module reload\' 1>>/dev/null', $out, $err );
	$start_ast = ($err != 0);
}

if ($start_ast) {
	echo "Asterisk not running. Starting Asterisk ...\n";
	
	/*
	$safe_asterisk = find_executable('safe_asterisk',
		array('/usr/sbin/', '/usr/bin/', '/usr/local/sbin/', '/usr/local/bin/'));
	if (! $safe_asterisk) {
		echo "safe_asterisk not found!\n";
		exit(1);
	}
	*/
	$err=0; $out=array();
	//@exec( 'asterisk 1>>/dev/null', $out, $err );
	//@exec( $safe_asterisk .' 1>>/dev/null', $out, $err );
	@exec( '/etc/init.d/asterisk start 1>>/dev/null', $out, $err );
	if ($err != 0) {
		echo "Failed to start Asterisk! ($err)\n";
		die(1);
	}
}
echo "Asterisk started.\n";


?>