#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

# NOT USED ANY MORE
#

define( 'GS_VALID', true );  /// this is a parent file
require_once( dirName(__FILE__) .'/../inc/conf.php' );

if ($argc != 2) {
	echo 'Usage: ', baseName($argv[0]), " <extension>\n";
	die(1);
}
$ext = preg_replace('/[^\d]/', '', $argv[1]);
if (! $ext) die();

$ret = array();

@chdir( '/var/spool/asterisk/voicemail/default/' );
$files = glob( $ext .'/*/*.txt' );
foreach ($files as $filename) {
	$tmp = explode('/', $filename, 3);
	
	$info['fld' ] = @$tmp[1];
	$info['file'] = baseName(@$tmp[2],'.txt');
	
	$msg = @gs_file_get_contents( $filename );
	
	preg_match('/^callerid\s*=\s*(.*)/mS', $msg, $m);
	$cid = @$m[1];
	preg_match('/<([^>]*)>$/S', $cid, $m);
	$cidnum = @$m[1];
	$cidname = trim(subStr( $cid, 0, -(strLen($cidnum)+2 )), ' "\'');
	$info['cidnum'] = trim($cidnum);
	$info['cidname'] = $cidname;
	
	preg_match('/^origtime\s*=\s*(.*)/mS', $msg, $m);
	$info['ts'] = (int)@$m[1];
	
	preg_match('/^duration\s*=\s*(.*)/mS', $msg, $m);
	$info['dur'] = (int)@$m[1];
	
	$ret[] = $info;
}

echo base64_encode( serialize( $ret ) ), "\n";


?>