#!/usr/bin/php -q
<?php
/*******************************************************************\
*            Gemeinschaft - asterisk cluster gemeinschaft
* 
* $Revision$
* 
* Copyright 2007, amooma GmbH, Bachstr. 126, 56566 Neuwied, Germany,
* http://www.amooma.de/
* Stefan Wintermeyer <stefan.wintermeyer@amooma.de>
* Philipp Kempgen <philipp.kempgen@amooma.de>
* Peter Kozak <peter.kozak@amooma.de>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
\*******************************************************************/

define( 'GS_VALID', true );  /// this is a parent file
require_once( dirName(__FILE__) .'/../inc/conf.php' );
require_once( GS_DIR .'inc/quote_shell_arg.php' );


if ($argc != 4) {
	echo 'Usage: ', baseName($argv[0]), " <extension> <folder> <msg>\n";
	exit(1);
}
$ext = preg_replace('/[^0-9]/'    , '', $argv[1]);
if (! $ext) exit(1);
$fld = preg_replace('/[^a-z0-9]/i', '', $argv[2]);
if (! $fld) exit(1);
$msg = preg_replace('/[^a-z0-9]/i', '', $argv[3]);
if (! $msg) exit(1);


$vmdir = '/var/spool/asterisk/voicemail/default/';
if (! @chDir( $vmdir )) {
	echo "Could not chdir to \"$vmdir\".\n";
	exit(1);
}
$files = glob( $ext .'/'. $fld .'/'. $msg .'.*' );
$ok = true;
$i=0;
foreach ($files as $filename) {
	++$i;
	$ok2 = @unlink($filename);
	$ok = $ok && $ok2;
}
if ($i < 1) {
	echo "No such message.\n";
	exit(0);
}
if (! $ok) {
	echo "ERROR. Failed to delete message.\n";
	exit(1);
}
echo "OK. Deleted.\n";


# run vm-postexec script as defined in etc/asterisk/voicemail.conf
# (externnotify)
$err=0; $out=array();
@exec( '/opt/gemeinschaft/dialplan-scripts/vm-postexec '. qsa('default') .' '. qsa($ext) .' '. qsa('999') .' 1>>/dev/null 2>>/dev/null', $out, $err );


?>