<?xml version="1.0" encoding="UTF-8"?>
<definitions name="generatecall"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="generatecall.wsdl"
	xmlns:tns="generatecall.wsdl"
	>
	<!-- $Revision$ -->
	
	
	<!-- array with structure array(array('key' => 'value'), ...) -->
	<!-- List of supported parameter keys:
		parameter name="CTIOutboundUser"
		parameter name="CTIOutboundTo"
		parameter name="CTIOutboundFrom"
		parameter name="CTIOutboundCIDnum"
		parameter name="CTIOutboundCLIR"
		parameter name="CTIOutboundPrv"
	-->
	<message name="GenerateCallRequest">
		<part name="data"       type="xsd:array"/>
		<!-- xsd:array is invalid but works -->
	</message>
	
	<!--
		errorcode .gt. 0: OK, errormsg is an empty string
		errorcode .lt. 0: ERROR, errormsg is filled
	-->
	<message name="GenerateCallResponse">
		<part name="errorcode" type="xsd:integer"/>
		<!--
		<part name="errormsg"  type="xsd:string"/>
		-->
	</message>
	
	<portType name="GenerateCallPortType">
		<operation name="generateCall">
			<input  message="tns:GenerateCallRequest"/>
			<output message="tns:GenerateCallResponse"/>
		</operation>
	</portType>
	
	<binding name="PBXSoapBinding" type="tns:GenerateCallPortType">
		<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="generateCall">
			<soap:operation soapAction="urn:callServer#generateCall"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
	
	<service name="GenerateCallService">
		<port name="GenerateCallPort" binding="tns:PBXSoapBinding">
			<soap:address location="http://dummy/soap/callServer.php"/>
		</port>
	</service>
	
</definitions>
